<?= $this->doctype() ?>

<html>
	<head>
        <meta charset="utf-8">
        <?= $this->headTitle('Первая браузерная игра с пенальным выводом средств')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
		<style>
			body {
				opacity: 0;
			}
		</style>
	</head>
    <body>
        <?php
            $this->headLink()->appendStylesheet($this->basePath('css/style.css'));
            $this->inlineScript()
                ->appendFile($this->basePath('js/jquery.min.js'))
                ->appendFile($this->basePath('js/vendor.js'))
                ->appendFile($this->basePath('js/custom.js'))
                ->appendFile($this->basePath('js/notify.js'))
                ->appendFile($this->basePath('js/system.js'));
        ?>
        <div class="wrapper">
            <?= $this->content ?>
        </div>
        <?= $this->headLink() ?>
        <?= $this->inlineScript() ?>
        <script src="/node/socket.io/socket.io.js"></script>
        <script>
            //var socket = io('http://www.ogame.zz:8000');
        </script>
        <script>
            SystemJS.config({
                baseURL: '<?= $this->basePath('/js/') ?>'
            });
            SystemJS.import('main.js');
        </script>
    </body>
</html>
