<?= $this->doctype() ?>

<html>
	<head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->translate('Title'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
	</head>
    <body>
        <?php
            $css = $this->currentRoute()->getRoute() == 'app' ? 'css/15.06.2017.style.css' : 'css/style.css';
            $custom = $this->currentRoute()->getRoute() == 'app' ? 'js/15.06.2017custom.js' : 'js/custom.js';
            $this->headLink()->appendStylesheet($this->basePath($css));
            $this->headLink()->appendStylesheet($this->basePath('css/custom.css'));
            $this->inlineScript()
                ->appendFile($this->basePath('js/jquery.min.js'))
                ->appendFile($this->basePath('js/vendor.js'))
                ->appendFile($this->basePath($custom))
                ->appendFile($this->basePath('js/notify.js'))
                ->appendFile($this->basePath('js/system.js'));
        ?>
        <div class="wrapper">
            <?= $this->content ?>
        </div>
        <?= $this->popup_contacts ?>
        <?= $this->popup_support ?>
        <?= $this->popup_rules ?>
        <?= $this->popup_confident ?>
        <?= $this->popup_conditions ?>
        <?= $this->headLink() ?>
        <?= $this->inlineScript() ?>
        <script src="/node/socket.io/socket.io.js"></script>
        <script>
            SystemJS.config({
                baseURL: '<?= $this->basePath('/js/') ?>'
            });
            SystemJS.import('main.js');
        </script>
    </body>
</html>
