<aside class="aside">
				<div class="aside__inner">
					<div class="aside__logo"></div>
					<div class="aside__menu js-scroll-wrap">
						<div class="aside__menu-item aside__menu-item_submenu">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-cup.svg" class="svg"></i></div>
								<div class="aside__menu-name"><?=$this->translate('Construction')?></div>
							</div>
							<div class="aside__submenu">
								<div class="aside__submenu-item">
									<div class="aside__submenu-link"><?=$this->translate('Subparagraph')?> 1</div>
								</div>
								<div class="aside__submenu-item">
									<div class="aside__submenu-link"><?=$this->translate('Subparagraph')?> 2</div>
								</div>
								<div class="aside__submenu-item">
									<div class="aside__submenu-link"><?=$this->translate('Subparagraph')?> 3</div>
								</div>
							</div>
						</div>
						<div class="aside__menu-item aside__menu-item_submenu">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-cup.svg" class="svg"></i></div>
								<div class="aside__menu-name"><?=$this->translate('Science')?></div>
							</div>
							<div class="aside__submenu">
								<div class="aside__submenu-item">
									<div class="aside__submenu-link"><?=$this->translate('Subparagraph')?> 1</div>
								</div>
								<div class="aside__submenu-item">
									<div class="aside__submenu-link"><?=$this->translate('Subparagraph')?> 2</div>
								</div>
								<div class="aside__submenu-item">
									<div class="aside__submenu-link"><?=$this->translate('Subparagraph')?> 3</div>
								</div>
							</div>
						</div>
						<div class="aside__menu-item">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-cup.svg" class="svg"></i></div>
								<div class="aside__menu-name"><?=$this->translate('Resources')?></div>
							</div>
						</div>
						<div class="aside__menu-item">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-cup.svg" class="svg"></i></div>
								<div class="aside__menu-name"><?=$this->translate('Messages')?> <span class="bgr_blue">5</span></div>
							</div>
						</div>
						<div class="aside__menu-item aside__menu-item_submenu">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-cup.svg" class="svg"></i></div>
								<div class="aside__menu-name"><?=$this->translate('Reportings')?> <span class="bgr_blue">497</span></div>
							</div>
							<div class="aside__submenu">
								<div class="aside__submenu-item">
									<div class="aside__submenu-link"><?=$this->translate('Subparagraph')?> 1</div>
								</div>
								<div class="aside__submenu-item">
									<div class="aside__submenu-link"><?=$this->translate('Subparagraph')?> 2</div>
								</div>
								<div class="aside__submenu-item">
									<div class="aside__submenu-link"><?=$this->translate('Subparagraph')?> 3</div>
								</div>
							</div>
						</div>
						<div class="aside__menu-item" data-popup=".popup_blackmarket">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-cup.svg" class="svg"></i></div>
								<div class="aside__menu-name"><?=$this->translate('Store')?> <span class="bgr_red">sale</span></div>
							</div>
						</div>
						<div class="aside__menu-item">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-settings.svg" class="svg"></i></div>
								<div class="aside__menu-name"><?=$this->translate('Statistics')?></div>
							</div>
						</div>
						<div class="aside__menu-item" data-menu_item="logout">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-user.svg" class="svg"></i></div>
								<div class="aside__menu-name"><?=$this->translate('Exit')?></div>
							</div>
						</div>
					</div>
				</div>
			</aside>
