<aside class="aside">
				<div class="aside__inner">
					<div class="aside__logo"></div>
					<div class="aside__menu js-scroll-wrap">
						<div class="aside__menu-item aside__menu-item_submenu">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-cup.svg" class="svg"></i></div>
								<div class="aside__menu-name">Строительство</div>
							</div>
							<div class="aside__submenu">
								<div class="aside__submenu-item">
									<div class="aside__submenu-link">Подпункт 1</div>
								</div>
								<div class="aside__submenu-item">
									<div class="aside__submenu-link">Подпункт 2</div>
								</div>
								<div class="aside__submenu-item">
									<div class="aside__submenu-link">Подпункт 3</div>
								</div>
							</div>
						</div>
						<div class="aside__menu-item aside__menu-item_submenu">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-cup.svg" class="svg"></i></div>
								<div class="aside__menu-name">Наука</div>
							</div>
							<div class="aside__submenu">
								<div class="aside__submenu-item">
									<div class="aside__submenu-link">Подпункт 1</div>
								</div>
								<div class="aside__submenu-item">
									<div class="aside__submenu-link">Подпункт 2</div>
								</div>
								<div class="aside__submenu-item">
									<div class="aside__submenu-link">Подпункт 3</div>
								</div>
							</div>
						</div>
						<div class="aside__menu-item">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-cup.svg" class="svg"></i></div>
								<div class="aside__menu-name">Ресурсы</div>
							</div>
						</div>
						<div class="aside__menu-item">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-cup.svg" class="svg"></i></div>
								<div class="aside__menu-name">Сообщения <span class="bgr_blue">5</span></div>
							</div>
						</div>
						<div class="aside__menu-item aside__menu-item_submenu">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-cup.svg" class="svg"></i></div>
								<div class="aside__menu-name">Оповещения <span class="bgr_blue">497</span></div>
							</div>
							<div class="aside__submenu">
								<div class="aside__submenu-item">
									<div class="aside__submenu-link">Подпункт 1</div>
								</div>
								<div class="aside__submenu-item">
									<div class="aside__submenu-link">Подпункт 2</div>
								</div>
								<div class="aside__submenu-item">
									<div class="aside__submenu-link">Подпункт 3</div>
								</div>
							</div>
						</div>
						<div class="aside__menu-item">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-cup.svg" class="svg"></i></div>
								<div class="aside__menu-name">Магазин <span class="bgr_red">sale</span></div>
							</div>
						</div>
						<div class="aside__menu-item">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-settings.svg" class="svg"></i></div>
								<div class="aside__menu-name">Статистика</div>
							</div>
						</div>
						<div class="aside__menu-item">
							<div class="aside__menu-link">
								<div class="aside__menu-ico"><i class="ico"><img src="/img/ico/ico-menu-user.svg" class="svg"></i></div>
								<div class="aside__menu-name">Выход</div>
							</div>
						</div>
					</div>
				</div>
			</aside>
