<div class="game">
    <div class="game__interface">
        <div class="game__galaxy"></div>
        
        <div class="game__planet">
            <div class="game__planet-name">
                <div class="val" data-current_planet="<?= $this->planet->getId(); ?>"><?= $this->planet->getName() ?></div>
                <i class="ico ico_action ico_edits"></i>
                <i class="ico ico_action ico_exit"></i> 
            </div>
            <div class="game__planet-view"><img src="/img/planets/06.png" alt=""></div>
            <?= $this->planetkeep; ?>
        </div>
        
        <div class="game__history">
            <div class="game__history-item game__history-item_message">
                <div class="game__history-status"></div>
                <div class="game__history-ico"><img src="/img/ico_history/ico-engine.svg" alt="" class="svg"></div>
                <div class="game__history-info">
                    <div class="game__history-tag"><span class="tag tag_time">02:03:02</span><span class="tag">АЛЬЯНС</span></div>
                    <div class="game__history-title">Истекает мирный договор</div>
                    <div class="game__history-text">Алья́нс (фр. Alliance) — союз, объединение (например, государств, организаций) на основе формальных либо неформальных договорных .</div>
                    <div class="game__history-text"><i class="ico ico-planet"><img src="/img/planets/01.png" alt="Планета Земля"></i> Планета Земля</div>
                    <div class="game__history-close ico ico_set ico_close"></div>
                    <a href="#" class="game__history-open ico ico_set ico_open"></a>
                </div>
            </div>
            <div class="game__history-item game__history-item_message game__history-item_good">
                <div class="game__history-status"></div>
                <div class="game__history-ico"><img src="/img/ico_history/ico-laser.svg" alt="" class="svg"></div>
                <div class="game__history-info">
                    <div class="game__history-tag"><span class="tag tag_time">02:03:02</span><span class="tag">АЛЬЯНС</span></div>
                    <div class="game__history-title">Истекает мирный договор</div>
                    <div class="game__history-close ico ico_set ico_close"></div>
                    <a href="#" class="game__history-open ico ico_set ico_open"></a>
                </div>
            </div>
            <div class="game__history-item game__history-item_message game__history-item_bad">
                <div class="game__history-status"></div>
                <div class="game__history-ico"><img src="/img/ico_history/ico-planet.svg" alt="" class="svg"></div>
                <div class="game__history-info">
                    <div class="game__history-tag"><span class="tag tag_time">02:03:02</span><span class="tag">АЛЬЯНС</span></div>
                    <div class="game__history-title">Истекает мирный договор</div>
                    <div class="game__history-close ico ico_set ico_close"></div>
                    <a href="#" class="game__history-open ico ico_set ico_open"></a>
                </div>
            </div>
            <div class="game__history-item game__history-item_message">
                <div class="game__history-status"></div>
                <div class="game__history-ico"><img src="/img/ico_history/ico-robot.svg" alt="" class="svg"></div>
                <div class="game__history-info">
                    <div class="game__history-tag"><span class="tag tag_time">02:03:02</span><span class="tag">АЛЬЯНС</span></div>
                    <div class="game__history-title">Истекает мирный договор</div>
                    <div class="game__history-text">Алья́нс (фр. Alliance) — союз, объединение (например, государств, организаций) на основе формальных либо неформальных договорных .</div>
                    <div class="game__history-text"><i class="ico ico-planet"><img src="/img/planets/01.png" alt="Планета Земля"></i> Планета Земля</div>
                    <div class="game__history-close ico ico_set ico_close"></div>
                    <a href="#" class="game__history-open ico ico_set ico_open"></a>
                </div>
            </div>
            <div class="game__history-item game__history-item_message">
                <div class="game__history-status"></div>
                <div class="game__history-ico"><img src="/img/ico_history/ico-veider.svg" alt="" class="svg"></div>
                <div class="game__history-info">
                    <div class="game__history-tag"><span class="tag tag_time">02:03:02</span><span class="tag">АЛЬЯНС</span></div>
                    <div class="game__history-title">Истекает мирный договор</div>
                    <div class="game__history-text">Алья́нс (фр. Alliance) — союз, объединение (например, государств, организаций) на основе формальных либо неформальных договорных .</div>
                    <div class="game__history-text"><i class="ico ico-planet"><img src="/img/planets/01.png" alt="Планета Земля"></i> Планета Земля</div>
                    <div class="game__history-close ico ico_set ico_close"></div>
                    <a href="#" class="game__history-open ico ico_set ico_open"></a>
                </div>
            </div>
            <a href="#" class="game__history-item game__history-item_btn">
                <div class="game__history-text">История</div>
            </a>
            <div class="game__history-item game__history-item_btn game__history-item_btn_half">
                <div class="game__history-val">
                    <div class="ico ico_set ico_settings"></div>
                </div>
            </div>
            <div class="game__history-item game__history-item_btn game__history-item_btn_half">
                <div class="game__history-val">
                    <div class="ico ico_set ico_delete"></div>
                </div>
            </div>
        </div>
        <div class="game__menu">
            <div class="game__menu-title">Меню</div>
            <a href="#" class="game__menu-item"><img src="/img/ico_simp/menu-ico-01.svg"></a>
            <a href="#" class="game__menu-item"><img src="/img/ico_simp/menu-ico-02.svg"></a>
            <a href="#" class="game__menu-item"><img src="/img/ico_simp/menu-ico-03.svg"></a>
        </div>
        <div class="game__attack">
            <div class="game__attack-item game__attack-item_attack">
                <div class="game__attack-preview">
                    <div class="game__attack-preview-ico"><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path fill="#ffffff" d="M16.13,4.475l-3.6,3.6L9.92,5.474l3.605-3.6L18.012,0ZM15.8,10.259l1.234,1.233-2.174,2.171L18,16.794l-1.195,1.193-3.137-3.132L11.5,17.025l-1.234-1.233,1.468-1.466L1.874,4.486-0.008.006,4.479,1.885l9.855,9.84ZM0.967,11.48L2.2,10.247,3.67,11.714l1.8-1.8,2.606,2.6-1.8,1.8,1.469,1.466L6.509,17.014l-2.174-2.17L1.2,17.975,0,16.783,3.14,13.65Z"/></svg>									</div>
                    <div class="game__attack-preview-rocket"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="14" viewBox="0 0 24 14"><path fill="#ffffff" d="M1.632,9.449v-4.9A7.467,7.467,0,0,1,2.494,4.14V9.86A7.442,7.442,0,0,1,1.632,9.449Zm8.695,2.092L7.862,14H0.225l3.7-3.7C3.7,10.252,3.5,10.056,3.31,10V3.941C3.5,3.889,3.7,3.764,3.93,3.712L0.225,0H7.862l2.464,2.469C17.614,1.2,24,7.014,24,7.014S17.614,12.809,10.326,11.541Zm4.146-6.814A2.273,2.273,0,1,0,16.741,7,2.271,2.271,0,0,0,14.472,4.727ZM0.862,9.11A7.442,7.442,0,0,1,0,8.7V5.3A7.467,7.467,0,0,1,.862,4.89V9.11Z"/></svg>									</div>
                    <div class="game__attack-preview-timer">00:00:00</div>
                </div>
                <div class="game__attack-inner">
                    <div class="game__attack-close ico ico_set ico_close"></div>
                    <a href="#" class="game__attack-open ico ico_set ico_open"></a>
                    <div class="game__attack-head">
                        <div class="game__attack-head-title">Вы атакуете</div>
                        <div title="Планету Хз" class="game__attack-head-planet"><span>Планету Хз</span> <i class="ico ico-planet"><img src="/img/planets/01.png" alt="Планета Хз"/></i></div>
                    </div>
                    <div class="game__attack-action">
                        <div class="game__attack-action-row game__attack-action-row_forward">
                            <div class="game__attack-action-title">Атака</div>
                            <div class="game__attack-action-line"></div>
                        </div>
                        <div class="game__attack-action-row game__attack-action-row_back">
                            <div class="game__attack-action-title">Возврат</div>
                            <div class="game__attack-action-line"></div>
                        </div>
                        <div class="game__attack-progress">
                            <div class="game__attack-progress-line">
                                <div style="width: 24%;" class="game__attack-progress-path">
                                    <div class="game__attack-progress-rocket"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="14" viewBox="0 0 24 14"><path fill="#ffffff" d="M1.632,9.449v-4.9A7.467,7.467,0,0,1,2.494,4.14V9.86A7.442,7.442,0,0,1,1.632,9.449Zm8.695,2.092L7.862,14H0.225l3.7-3.7C3.7,10.252,3.5,10.056,3.31,10V3.941C3.5,3.889,3.7,3.764,3.93,3.712L0.225,0H7.862l2.464,2.469C17.614,1.2,24,7.014,24,7.014S17.614,12.809,10.326,11.541Zm4.146-6.814A2.273,2.273,0,1,0,16.741,7,2.271,2.271,0,0,0,14.472,4.727ZM0.862,9.11A7.442,7.442,0,0,1,0,8.7V5.3A7.467,7.467,0,0,1,.862,4.89V9.11Z"/></svg>													</div>
                                </div>
                            </div>
                            <div class="game__attack-progress-timer">00:00:00</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="game__attack-item game__attack-item_attack game__attack-item_back">
                <div class="game__attack-preview">
                    <div class="game__attack-preview-ico"><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path fill="#ffffff" d="M16.13,4.475l-3.6,3.6L9.92,5.474l3.605-3.6L18.012,0ZM15.8,10.259l1.234,1.233-2.174,2.171L18,16.794l-1.195,1.193-3.137-3.132L11.5,17.025l-1.234-1.233,1.468-1.466L1.874,4.486-0.008.006,4.479,1.885l9.855,9.84ZM0.967,11.48L2.2,10.247,3.67,11.714l1.8-1.8,2.606,2.6-1.8,1.8,1.469,1.466L6.509,17.014l-2.174-2.17L1.2,17.975,0,16.783,3.14,13.65Z"/></svg>									</div>
                    <div class="game__attack-preview-rocket"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="14" viewBox="0 0 24 14"><path fill="#ffffff" d="M1.632,9.449v-4.9A7.467,7.467,0,0,1,2.494,4.14V9.86A7.442,7.442,0,0,1,1.632,9.449Zm8.695,2.092L7.862,14H0.225l3.7-3.7C3.7,10.252,3.5,10.056,3.31,10V3.941C3.5,3.889,3.7,3.764,3.93,3.712L0.225,0H7.862l2.464,2.469C17.614,1.2,24,7.014,24,7.014S17.614,12.809,10.326,11.541Zm4.146-6.814A2.273,2.273,0,1,0,16.741,7,2.271,2.271,0,0,0,14.472,4.727ZM0.862,9.11A7.442,7.442,0,0,1,0,8.7V5.3A7.467,7.467,0,0,1,.862,4.89V9.11Z"/></svg>									</div>
                    <div class="game__attack-preview-timer">Возврат</div>
                </div>
                <div class="game__attack-inner">
                    <div class="game__attack-close ico ico_set ico_close"></div>
                    <a href="#" class="game__attack-open ico ico_set ico_open"></a>
                    <div class="game__attack-head">
                        <div class="game__attack-head-title">Вы атакуете</div>
                        <div title="Планету Хз" class="game__attack-head-planet"><span>Планету Хз</span> <i class="ico ico-planet"><img src="/img/planets/01.png" alt="Планета Хз"/></i></div>
                    </div>
                    <div class="game__attack-action">
                        <div class="game__attack-action-row game__attack-action-row_forward">
                            <div class="game__attack-action-title">Атака</div>
                            <div class="game__attack-action-line"></div>
                        </div>
                        <div class="game__attack-action-row game__attack-action-row_back">
                            <div class="game__attack-action-title">Возврат</div>
                            <div class="game__attack-action-line"></div>
                        </div>
                        <div class="game__attack-progress">
                            <div class="game__attack-progress-line">
                                <div style="width: 24%;" class="game__attack-progress-path">
                                    <div class="game__attack-progress-rocket"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="14" viewBox="0 0 24 14"><path fill="#ffffff" d="M1.632,9.449v-4.9A7.467,7.467,0,0,1,2.494,4.14V9.86A7.442,7.442,0,0,1,1.632,9.449Zm8.695,2.092L7.862,14H0.225l3.7-3.7C3.7,10.252,3.5,10.056,3.31,10V3.941C3.5,3.889,3.7,3.764,3.93,3.712L0.225,0H7.862l2.464,2.469C17.614,1.2,24,7.014,24,7.014S17.614,12.809,10.326,11.541Zm4.146-6.814A2.273,2.273,0,1,0,16.741,7,2.271,2.271,0,0,0,14.472,4.727ZM0.862,9.11A7.442,7.442,0,0,1,0,8.7V5.3A7.467,7.467,0,0,1,.862,4.89V9.11Z"/></svg>													</div>
                                </div>
                            </div>
                            <div class="game__attack-progress-timer">00:00:00</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="game__attack-item game__attack-item_protect">
                <div class="game__attack-preview">
                    <div class="game__attack-preview-ico"><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path fill="#ffffff" d="M16.13,4.475l-3.6,3.6L9.92,5.474l3.605-3.6L18.012,0ZM15.8,10.259l1.234,1.233-2.174,2.171L18,16.794l-1.195,1.193-3.137-3.132L11.5,17.025l-1.234-1.233,1.468-1.466L1.874,4.486-0.008.006,4.479,1.885l9.855,9.84ZM0.967,11.48L2.2,10.247,3.67,11.714l1.8-1.8,2.606,2.6-1.8,1.8,1.469,1.466L6.509,17.014l-2.174-2.17L1.2,17.975,0,16.783,3.14,13.65Z"/></svg>									</div>
                    <div class="game__attack-preview-rocket"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="14" viewBox="0 0 24 14"><path fill="#ffffff" d="M1.632,9.449v-4.9A7.467,7.467,0,0,1,2.494,4.14V9.86A7.442,7.442,0,0,1,1.632,9.449Zm8.695,2.092L7.862,14H0.225l3.7-3.7C3.7,10.252,3.5,10.056,3.31,10V3.941C3.5,3.889,3.7,3.764,3.93,3.712L0.225,0H7.862l2.464,2.469C17.614,1.2,24,7.014,24,7.014S17.614,12.809,10.326,11.541Zm4.146-6.814A2.273,2.273,0,1,0,16.741,7,2.271,2.271,0,0,0,14.472,4.727ZM0.862,9.11A7.442,7.442,0,0,1,0,8.7V5.3A7.467,7.467,0,0,1,.862,4.89V9.11Z"/></svg>									</div>
                    <div class="game__attack-preview-timer">00:00:00</div>
                </div>
                <div class="game__attack-inner">
                    <div class="game__attack-close ico ico_set ico_close"></div>
                    <a href="#" class="game__attack-open ico ico_set ico_open"></a>
                    <div class="game__attack-head">
                        <div class="game__attack-head-title">Вас атакует</div>
                        <div title="Планета Хз" class="game__attack-head-planet"><span>Планета Хз</span> <i class="ico ico-planet"><img src="/img/planets/01.png" alt="Планета Хз"/></i></div>
                    </div>
                    <div class="game__attack-action">
                        <div class="game__attack-action-row game__attack-action-row_forward">
                            <div class="game__attack-action-title">Атака</div>
                            <div class="game__attack-action-line"></div>
                        </div>
                        <div class="game__attack-action-row game__attack-action-row_back">
                            <div class="game__attack-action-title">Возврат</div>
                            <div class="game__attack-action-line"></div>
                        </div>
                        <div class="game__attack-progress">
                            <div class="game__attack-progress-line">
                                <div style="width: 24%;" class="game__attack-progress-path">
                                    <div class="game__attack-progress-rocket"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="14" viewBox="0 0 24 14"><path fill="#ffffff" d="M1.632,9.449v-4.9A7.467,7.467,0,0,1,2.494,4.14V9.86A7.442,7.442,0,0,1,1.632,9.449Zm8.695,2.092L7.862,14H0.225l3.7-3.7C3.7,10.252,3.5,10.056,3.31,10V3.941C3.5,3.889,3.7,3.764,3.93,3.712L0.225,0H7.862l2.464,2.469C17.614,1.2,24,7.014,24,7.014S17.614,12.809,10.326,11.541Zm4.146-6.814A2.273,2.273,0,1,0,16.741,7,2.271,2.271,0,0,0,14.472,4.727ZM0.862,9.11A7.442,7.442,0,0,1,0,8.7V5.3A7.467,7.467,0,0,1,.862,4.89V9.11Z"/></svg>													</div>
                                </div>
                            </div>
                            <div class="game__attack-progress-timer">00:00:00</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="game__attack-item game__attack-item_protect game__attack-item_back">
                <div class="game__attack-preview">
                    <div class="game__attack-preview-ico"><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path fill="#ffffff" d="M16.13,4.475l-3.6,3.6L9.92,5.474l3.605-3.6L18.012,0ZM15.8,10.259l1.234,1.233-2.174,2.171L18,16.794l-1.195,1.193-3.137-3.132L11.5,17.025l-1.234-1.233,1.468-1.466L1.874,4.486-0.008.006,4.479,1.885l9.855,9.84ZM0.967,11.48L2.2,10.247,3.67,11.714l1.8-1.8,2.606,2.6-1.8,1.8,1.469,1.466L6.509,17.014l-2.174-2.17L1.2,17.975,0,16.783,3.14,13.65Z"/></svg>									</div>
                    <div class="game__attack-preview-rocket"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="14" viewBox="0 0 24 14"><path fill="#ffffff" d="M1.632,9.449v-4.9A7.467,7.467,0,0,1,2.494,4.14V9.86A7.442,7.442,0,0,1,1.632,9.449Zm8.695,2.092L7.862,14H0.225l3.7-3.7C3.7,10.252,3.5,10.056,3.31,10V3.941C3.5,3.889,3.7,3.764,3.93,3.712L0.225,0H7.862l2.464,2.469C17.614,1.2,24,7.014,24,7.014S17.614,12.809,10.326,11.541Zm4.146-6.814A2.273,2.273,0,1,0,16.741,7,2.271,2.271,0,0,0,14.472,4.727ZM0.862,9.11A7.442,7.442,0,0,1,0,8.7V5.3A7.467,7.467,0,0,1,.862,4.89V9.11Z"/></svg>									</div>
                    <div class="game__attack-preview-timer">Возврат</div>
                </div>
                <div class="game__attack-inner">
                    <div class="game__attack-close ico ico_set ico_close"></div>
                    <a href="#" class="game__attack-open ico ico_set ico_open"></a>
                    <div class="game__attack-head">
                        <div class="game__attack-head-title">Вас атакует</div>
                        <div title="Планета Хз" class="game__attack-head-planet"><span>Планета Хз</span> <i class="ico ico-planet"><img src="/img/planets/01.png" alt="Планета Хз"/></i></div>
                    </div>
                    <div class="game__attack-action">
                        <div class="game__attack-action-row game__attack-action-row_forward">
                            <div class="game__attack-action-title">Атака</div>
                            <div class="game__attack-action-line"></div>
                        </div>
                        <div class="game__attack-action-row game__attack-action-row_back">
                            <div class="game__attack-action-title">Возврат</div>
                            <div class="game__attack-action-line"></div>
                        </div>
                        <div class="game__attack-progress">
                            <div class="game__attack-progress-line">
                                <div style="width: 24%;" class="game__attack-progress-path">
                                    <div class="game__attack-progress-rocket"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="14" viewBox="0 0 24 14"><path fill="#ffffff" d="M1.632,9.449v-4.9A7.467,7.467,0,0,1,2.494,4.14V9.86A7.442,7.442,0,0,1,1.632,9.449Zm8.695,2.092L7.862,14H0.225l3.7-3.7C3.7,10.252,3.5,10.056,3.31,10V3.941C3.5,3.889,3.7,3.764,3.93,3.712L0.225,0H7.862l2.464,2.469C17.614,1.2,24,7.014,24,7.014S17.614,12.809,10.326,11.541Zm4.146-6.814A2.273,2.273,0,1,0,16.741,7,2.271,2.271,0,0,0,14.472,4.727ZM0.862,9.11A7.442,7.442,0,0,1,0,8.7V5.3A7.467,7.467,0,0,1,.862,4.89V9.11Z"/></svg>													</div>
                                </div>
                            </div>
                            <div class="game__attack-progress-timer">00:00:00</div>
                        </div>
                    </div>
                </div>
            </div>
            <a href="#" class="game__attack-item">
                <div class="game__attack-text">Весь флот - 134</div>
            </a>
        </div>
        <div class="game__satellite">
            <div class="game__satellite-item">
                <div class="game__satellite-planet"><img src="/img/planets/01.png"></div>
                <div class="game__satellite-info">
                    <div class="game__satellite-title"><span>Спутник Луна 1</span>
                        <a href="#" class="ico ico_action ico_edits"> </a>
                    </div>
                    <div class="game__satellite-text">&Oslash; 12.800 км<br>>от -11С&deg; до 12С&deg;<br> Место в галактике [1:390:10]</div>
                </div>
            </div>
            <div class="game__satellite-item">
                <div class="game__satellite-planet"><img src="/img/planets/02.png"></div>
                <div class="game__satellite-info">
                    <div class="game__satellite-title"><span>Спутник Луна 2</span>
                        <a href="#" class="ico ico_action ico_edits"> </a>
                    </div>
                    <div class="game__satellite-text">&Oslash; 12.800 км<br>>от -11С&deg; до 12С&deg;<br> Место в галактике [1:390:10]</div>
                </div>
            </div>
            <div class="game__satellite-item">
                <div class="game__satellite-planet"><img src="/img/planets/03.png"></div>
                <div class="game__satellite-attaked">
                    <a href="#"></a>
                </div>
                <div class="game__satellite-info">
                    <div class="game__satellite-title"><span>Спутник Луна 3</span>
                        <a href="#" class="ico ico_action ico_edits"> </a>
                    </div>
                    <div class="game__satellite-text">&Oslash; 12.800 км<br>>от -11С&deg; до 12С&deg;<br> Место в галактике [1:390:10]</div>
                </div>
            </div>
            <div class="game__satellite-item">
                <div class="game__satellite-planet"><img src="/img/planets/04.png"></div>
                <div class="game__satellite-info">
                    <div class="game__satellite-title"><span>Спутник Луна 4</span>
                        <a href="#" class="ico ico_action ico_edits"> </a>
                    </div>
                    <div class="game__satellite-text">&Oslash; 12.800 км<br>>от -11С&deg; до 12С&deg;<br> Место в галактике [1:390:10]</div>
                </div>
            </div>
            <div class="game__satellite-item">
                <div class="game__satellite-planet"><img src="/img/planets/05.png"></div>
                <div class="game__satellite-info">
                    <div class="game__satellite-title"><span>Спутник Луна 5</span>
                        <a href="#" class="ico ico_action ico_edits"> </a>
                    </div>
                    <div class="game__satellite-text">&Oslash; 12.800 км<br>>от -11С&deg; до 12С&deg;<br> Место в галактике [1:390:10]</div>
                </div>
            </div>
            <div class="game__satellite-item">
                <div class="game__satellite-planet"><img src="/img/planets/06.png"></div>
                <div class="game__satellite-info">
                    <div class="game__satellite-title"><span>Спутник Луна 6</span>
                        <a href="#" class="ico ico_action ico_edits"> </a>
                    </div>
                    <div class="game__satellite-text">&Oslash; 12.800 км<br>>от -11С&deg; до 12С&deg;<br> Место в галактике [1:390:10]</div>
                </div>
            </div>
        </div>

    </div>
</div>
<?= $this->popup_building ?>
<?= $this->fleet_forward_1 ?>
<?= $this->fleet_forward_2 ?>
<?= $this->fleet_forward_3 ?>
<?= $this->blackmarket ?>
<?= $this->buy ?>
