<header class="header" 
    data-entity_user="<?= $user->getId() ?>"
    data-entity_planet="<?= $planet->getId() ?>">
    <div class="header__inner">
        <div class="header__item header__item_menu js-toggle-asidemenu">
            <div class="header__item-val"><i class="ico ico_action ico_menu"></i></div>
        </div>
        <div class="header__item header__item_messenger">
            <div class="header__item-val"><i class="ico ico_action ico_messenger"></i><i class="ico ico_count">12</i></div>
        </div>
        <div class="header__item header__item_events">
            <div class="header__item-val"><i class="ico ico_action ico_events"></i><i class="ico ico_count">99+</i></div>
        </div>

        <?= $electricity ?>
        <?= $metall ?>
        <?= $heavygas ?>
        <?= $ore ?>
        <?= $hydro ?>
        <?= $titan ?>
        <?= $darkmatter ?>
        <?= $redmatter ?>
        <?= $anti ?>
                    
        <div class="header__place">
            <div class="header__item header__item_planet">
                <div class="header__item-val">
                    <div class="ico ico-planet">
                        <img src="/img/planets/01.png" alt="Планета Земля">
                    </div>
                    <div class="val">Планета Земля</div>
                    <i class="ico ico_action ico_open"></i> 
                </div>
            </div>
            <div class="header__item header__item_space">
                <div class="header__item-val">
                    <i class="ico ico_vortex"></i>
                    <div class="val">Вселенная</div>
                    <i class="ico ico_action ico_open"></i> 
                </div>
            </div>
        </div>
    </div>
    <div class="header__line"></div>
</header>
