<div class="storage__col">
    <div class="storage__col-title">Заводы</div>
    <div style="color: #e8473b;" class="storage__item storage__item_done"
        data-root="root"
        data-entity="Plants-build-block-main"
        data-event_id="<?= $is_building ? $event->getId() : 0 ?>"
        data-event_begin="<?= $is_building ? $event->getEventBegin() : 0 ?>"
        data-event_end="<?= $is_building ? $event->getEventEnd() : 0 ?>"
        data-event_now="<?= time() ?>"
        data-building_id="<?= $is_building ? $event->getTargetBuildingType()->getId() : 0 ?>"
    >
        <div class="storage__item-inner <?= $is_building ? "display" : "no-display"; ?>" data-entity="building-column">
            <div class="storage__item-plate">
                <div class="storage__item-plate-close ico ico_set ico_close"></div>
                <div class="storage__item-plate-title"><?= $is_building ? $event->getName() : '' ?></div>
                <div class="storage__item-plate-btns">
                    <div class="btn" data-entity="finish_4_donate_building_button">Достроить</div>
                </div>
            </div>
            <div class="storage__item-frame" data-entity="process-ico">
                <svg class="storage_ico" xmlns="http://www.w3.org/2000/svg" width="54" height="54" viewBox="0 0 54 54">
  <path class="storage_ico-lock" d="M680.382,48.335H680.2V46.981a2.88,2.88,0,0,0-5.76,0v1.354h-0.178a1.352,1.352,0,0,0-1.355,1.35v3.038a1.352,1.352,0,0,0,1.355,1.35h6.116a1.353,1.353,0,0,0,1.355-1.35V49.686A1.353,1.353,0,0,0,680.382,48.335Zm-4.233-1.354a1.175,1.175,0,0,1,2.349,0v1.354h-2.349V46.981Z" transform="translate(-650.5 -19.922)"/>
  <path class="storage_ico-ready" d="M682.049,51.09l-1.6,1.646a0.675,0.675,0,0,1-.972,0l-3.848-3.95a1.379,1.379,0,0,1-.389-1l0.031-1.343a0.658,0.658,0,0,1,.654-0.652l1.4,0.007a1.313,1.313,0,0,1,.933.4l3.791,3.891A0.72,0.72,0,0,1,682.049,51.09Zm-4.725.993-3.48,3.572a0.336,0.336,0,0,1-.483,0l-1.011-1.038a0.357,0.357,0,0,1,0-.5l3.48-3.572Z" transform="translate(-650.5 -19.922)"/>
  <path class="storage_ico-inner" d="M656.75,67.027V30.234l17,7.83v-7.83l23,10.631V67.027h-40Zm33.179-37.789,6.821,3.142v4.842l-6.821-3.142V29.238Z" transform="translate(-650.5 -19.922)"/>
  <path class="storage_ico-frame" d="M686.5,22.413l16,7.025v42h-50v-49l15.584,7.109,1.416,0.646V22.437l15.584,7.109,1.416,0.646V22.612" transform="translate(-650.5 -19.922)"/>
                </svg> 
            </div>
            <div class="storage__item-ico"
                 data-entity="building-ico">
                <svg xmlns="http://www.w3.org/2000/svg" width="54" height="54" viewBox="0 0 54 54">
  <path d="M33.145,46.1V33.711l1.6-4.82h3.2l1.6,4.82V46.1H33.145Zm1.6-23.722,1.6-6.427,1.6,6.427v4.9h-3.2v-4.9ZM23.553,33.711l1.6-4.82h3.2l1.6,4.82V46.1h-6.4V33.711Zm1.6-11.331,1.6-6.427,1.6,6.427v4.9h-3.2v-4.9ZM13.96,33.711l1.6-4.82h3.2l1.6,4.82V46.1H13.96V33.711Zm1.6-11.331,1.6-6.427,1.6,6.427v4.9h-3.2v-4.9Z" transform="translate(0.25 -4.031)"/>
                </svg> 
            </div>
            <div style="height:<?= $progress ?>%;" 
                 class="storage__item-progress" 
                 data-entity="progress"
                 data-entity_progress="<?php if($is_building) { echo  $event->getId(); } ?>">
                <svg class="storage_ico" xmlns="http://www.w3.org/2000/svg" width="54" height="54" viewBox="0 0 54 54">
  <path class="storage_ico-lock" d="M680.382,48.335H680.2V46.981a2.88,2.88,0,0,0-5.76,0v1.354h-0.178a1.352,1.352,0,0,0-1.355,1.35v3.038a1.352,1.352,0,0,0,1.355,1.35h6.116a1.353,1.353,0,0,0,1.355-1.35V49.686A1.353,1.353,0,0,0,680.382,48.335Zm-4.233-1.354a1.175,1.175,0,0,1,2.349,0v1.354h-2.349V46.981Z" transform="translate(-650.5 -19.922)"/>
  <path class="storage_ico-ready" d="M682.049,51.09l-1.6,1.646a0.675,0.675,0,0,1-.972,0l-3.848-3.95a1.379,1.379,0,0,1-.389-1l0.031-1.343a0.658,0.658,0,0,1,.654-0.652l1.4,0.007a1.313,1.313,0,0,1,.933.4l3.791,3.891A0.72,0.72,0,0,1,682.049,51.09Zm-4.725.993-3.48,3.572a0.336,0.336,0,0,1-.483,0l-1.011-1.038a0.357,0.357,0,0,1,0-.5l3.48-3.572Z" transform="translate(-650.5 -19.922)"/>
  <path class="storage_ico-inner" d="M656.75,67.027V30.234l17,7.83v-7.83l23,10.631V67.027h-40Zm33.179-37.789,6.821,3.142v4.842l-6.821-3.142V29.238Z" transform="translate(-650.5 -19.922)"/>
  <path class="storage_ico-frame" d="M686.5,22.413l16,7.025v42h-50v-49l15.584,7.109,1.416,0.646V22.437l15.584,7.109,1.416,0.646V22.612" transform="translate(-650.5 -19.922)"/>
                </svg> 
            </div>
            
            <div class="storage__item-timer"
                 data-entity="timer-wrap">
                <span>
                    <i data-entity="timer"><?= $hours?>:<?= $minutes?>:<?= $seconds?></i>
                </span>
            </div>
            
        </div>
    </div>
    <div style="" class="storage__item storage__item_ready <?= !$is_building ? "display" : "no-display"; ?>"
         data-entity="hammer"
         data-tab-popup="building_industrials"
         data-process="source-building-process-slot-1">
        <div class="storage__item-inner">
            <div class="storage__item-frame">
                <svg class="storage_ico" xmlns="http://www.w3.org/2000/svg" width="54" height="54" viewBox="0 0 54 54">
  <path class="storage_ico-lock" d="M680.382,48.335H680.2V46.981a2.88,2.88,0,0,0-5.76,0v1.354h-0.178a1.352,1.352,0,0,0-1.355,1.35v3.038a1.352,1.352,0,0,0,1.355,1.35h6.116a1.353,1.353,0,0,0,1.355-1.35V49.686A1.353,1.353,0,0,0,680.382,48.335Zm-4.233-1.354a1.175,1.175,0,0,1,2.349,0v1.354h-2.349V46.981Z" transform="translate(-650.5 -19.922)"/>
  <path class="storage_ico-ready" d="M682.049,51.09l-1.6,1.646a0.675,0.675,0,0,1-.972,0l-3.848-3.95a1.379,1.379,0,0,1-.389-1l0.031-1.343a0.658,0.658,0,0,1,.654-0.652l1.4,0.007a1.313,1.313,0,0,1,.933.4l3.791,3.891A0.72,0.72,0,0,1,682.049,51.09Zm-4.725.993-3.48,3.572a0.336,0.336,0,0,1-.483,0l-1.011-1.038a0.357,0.357,0,0,1,0-.5l3.48-3.572Z" transform="translate(-650.5 -19.922)"/>
  <path class="storage_ico-inner" d="M656.75,67.027V30.234l17,7.83v-7.83l23,10.631V67.027h-40Zm33.179-37.789,6.821,3.142v4.842l-6.821-3.142V29.238Z" transform="translate(-650.5 -19.922)"/>
  <path class="storage_ico-frame" d="M686.5,22.413l16,7.025v42h-50v-49l15.584,7.109,1.416,0.646V22.437l15.584,7.109,1.416,0.646V22.612" transform="translate(-650.5 -19.922)"/>
                </svg> 
            </div>
        </div>
    </div>
    <div style="" class="storage__item storage__item_lock" data-locked="industrial-building-locked-slot-1">
        <div class="storage__item-inner">
            <div class="storage__item-frame">
                <svg class="storage_ico" xmlns="http://www.w3.org/2000/svg" width="54" height="54" viewBox="0 0 54 54">
  <path class="storage_ico-lock" d="M680.382,48.335H680.2V46.981a2.88,2.88,0,0,0-5.76,0v1.354h-0.178a1.352,1.352,0,0,0-1.355,1.35v3.038a1.352,1.352,0,0,0,1.355,1.35h6.116a1.353,1.353,0,0,0,1.355-1.35V49.686A1.353,1.353,0,0,0,680.382,48.335Zm-4.233-1.354a1.175,1.175,0,0,1,2.349,0v1.354h-2.349V46.981Z" transform="translate(-650.5 -19.922)"/>
  <path class="storage_ico-ready" d="M682.049,51.09l-1.6,1.646a0.675,0.675,0,0,1-.972,0l-3.848-3.95a1.379,1.379,0,0,1-.389-1l0.031-1.343a0.658,0.658,0,0,1,.654-0.652l1.4,0.007a1.313,1.313,0,0,1,.933.4l3.791,3.891A0.72,0.72,0,0,1,682.049,51.09Zm-4.725.993-3.48,3.572a0.336,0.336,0,0,1-.483,0l-1.011-1.038a0.357,0.357,0,0,1,0-.5l3.48-3.572Z" transform="translate(-650.5 -19.922)"/>
  <path class="storage_ico-inner" d="M656.75,67.027V30.234l17,7.83v-7.83l23,10.631V67.027h-40Zm33.179-37.789,6.821,3.142v4.842l-6.821-3.142V29.238Z" transform="translate(-650.5 -19.922)"/>
  <path class="storage_ico-frame" d="M686.5,22.413l16,7.025v42h-50v-49l15.584,7.109,1.416,0.646V22.437l15.584,7.109,1.416,0.646V22.612" transform="translate(-650.5 -19.922)"/>
                </svg> 
            </div>
        </div>
    </div>
</div>
<!--
<div class="storage__col">
    <div class="storage__col-title"><?=$this->translate('Plants')?></div>
    <div class="keep__item clr_red" 
        data-root="root"
        data-entity="industrial-build-block-main" 
        data-event_id="<?= $is_building ? $event->getId() : 0 ?>"
        data-event_begin="<?= $is_building ? $event->getEventBegin() : 0 ?>"
        data-event_end="<?= $is_building ? $event->getEventEnd() : 0 ?>"
        data-event_now="<?= time() ?>"
        data-building_id="<?= $is_building ? $event->getTargetBuildingType()->getId() : 0 ?>"
    >
        <div class="keep__item-info" <?php if(! $is_building) : ?>style="display: none"<?php endif; ?>>
            <div class="keep__item-info-header"><a href="#" class="btn">1,5x</a><a href="#" class="btn">2x</a></div>
            <div class="keep__item-info-text"> <?= $is_building ? $event->getName() : '' ?></div>
            <div class="keep__item-info-close">
                <i class="ico">
                    <svg class="svg" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path fill="#ffffff" d="M415.7,397.8l2.72-2.72a2.349,2.349,0,0,0-3.323-3.322l-2.719,2.719-2.719-2.719a2.349,2.349,0,0,0-3.322,3.322l2.719,2.72-2.719,2.719a2.349,2.349,0,0,0,3.322,3.323l2.719-2.72,2.719,2.72a2.35,2.35,0,0,0,3.323-3.323Z" transform="translate(-402.406 -387.813)"/></svg>
                </i>
                <span class="value" data-entity="reject_building_button"><?=$this->translate('Cancel')?></span>
            </div>
        </div>
        <div class="keep__item-preview"
            data-process_window="industrials-building-process-block"
            data-popup="<?php if($is_building) : ?>_<?php endif; ?>.popup_building" 
            data-popup_id="popup_building" 
            data-tab_open="building_resources" 
            style="cursor: pointer; display: <?php if(!$is_building) : ?>none<?php else : ?>block<?php endif; ?>"
        >
            <div 
                data-entity_progress="<?php if($is_building) { echo  $event->getId(); } ?>"
                style="height:<?= $progress ?>%;" 
                class="keep__item-preview-progress">
                <i>
                    <svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81Z" transform="translate(4.5 4.5)"/></svg>
                </i>
            </div>
        </div>
        <div class="keep__item-timer"
             style="display: <?php if(!$is_building) : ?>none<?php else : ?>block<?php endif; ?>"
        >
            <span>
                <i data-entity="timer"><?= $hours?>:<?= $minutes?>:<?= $seconds?></i>
            </span>
        </div>
        <div class="keep__item clr_red" 
             data-popup=".popup_building"
             data-process="industrial-building-process-slot-1" 
             style="display: <?php if(!$is_building) : ?>block<?php else : ?>none<?php endif; ?>;"
        >
            <div class="keep__item-preview">
                <div class="keep__item-preview-frame">
                    <i class="ik ik_factories ik_ready"></i>
                </div>
            </div>
        </div>
	</div>
    
	<div class="keep__item clr_red" data-locked="industrial-building-locked-slot-1">
		<div class="keep__item-preview">
			<div class="keep__item-preview-frame">
                <i class="ik ik_factories ik_locked"></i>
            </div>
		</div>
	</div>
	
</div>
-->
