<div class="keep__column keep__column_middle">
    <div class="keep__column-title">Ресурсы</div>
    <div class="keep__item clr_brown" data-entity="resources-build-block" data-event_id="<?php if($is_building) { echo $event->getId(); } ?>">
		<?php if($is_building) : ?>
        <div class="keep__item-info">
			<div class="keep__item-info-header"><a href="#" class="btn">1,5x</a><a href="#" class="btn">2x</a></div>
			<div class="keep__item-info-text"> <?= $event->getName() ?></div>
			<div class="keep__item-info-close">
                <i class="ico">
                    <svg class="svg" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path fill="#ffffff" d="M415.7,397.8l2.72-2.72a2.349,2.349,0,0,0-3.323-3.322l-2.719,2.719-2.719-2.719a2.349,2.349,0,0,0-3.322,3.322l2.719,2.72-2.719,2.719a2.349,2.349,0,0,0,3.322,3.323l2.719-2.72,2.719,2.72a2.35,2.35,0,0,0,3.323-3.323Z" transform="translate(-402.406 -387.813)"/></svg>
                </i>
                <span class="value" data-entity="reject_building_button_<?= $event->getId()?>">Отмена</span>
            </div>
		</div>
        <?php endif; ?>
		<div class="keep__item-preview" <?php if(!$is_building) :?>data-popup=".popup_building" data-popup_id="popup_building" data-tab_open="resource" style="cursor: pointer;"<?php endif; ?>>
			<div data-entity_progress="<?php if($is_building) { echo  $event->getId(); } ?>" style="height:<?= $progress ?>%;" class="keep__item-preview-progress">
                <i>
                    <svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M75.984,80.975H-0.008V23.511l0.481-.295L38.539-.013,75.984,23.519V80.975Z" transform="translate(7.016 4.516)"/></svg>
                </i>
            </div>
			<div class="keep__item-preview-frame">
                <i>
                    <svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M75.984,80.975H-0.008V23.511l0.481-.295L38.539-.013,75.984,23.519V80.975ZM2,78.963H73.977V24.633L38.523,2.353,2,24.641V78.963Z" transform="translate(7.016 4.516)"/></svg>
                </i>
            </div>
			<div class="keep__item-preview-ico">
                <i>
                    <svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M6.241,0.684L10.3,7.671,0.765,7.646Zm15.3-.2L29.131,7.72,12.672,7.677l7.675-7.19h1.191Zm1.6,0H34.481l-4.1,6.892Zm6.526,8.34-8.72,21.824L12.056,8.781ZM11.38,7.373L7.393,0.487H18.73Zm-0.5,1.4,8.039,19.755L0.58,8.751ZM30.848,8.83L41.223,8.857,22.939,28.579Zm0.6-1.1,4.205-7.051,5.566,7.077Z" transform="translate(24.094 33)"/></svg>
                </i>
            </div>
		</div>
		<div class="keep__item-timer"><span><i data-entity="timer"><?= $hours?>:<?= $minutes?>:<?= $seconds?></i></span></div>
	</div>
    <?php if($is_building) : ?>
	<div class="keep__item clr_brown" data-entity="source-building-process">
        <div class="keep__item-preview">
			<div class="keep__item-preview-frame"><i><img src="/img/keep/resources-ready.svg" alt="" class="svg"/></i></div>
		</div>
	</div>
    <?php endif; ?>
	<div class="keep__item clr_brown">
		<div class="keep__item-preview">
			<div class="keep__item-preview-frame"><i><img src="/img/keep/resources-locked.svg" alt="" class="svg"/></i></div>
        </div>
	</div>
</div>
