<div class="keep__column">
    <div class="keep__column-title">Заводы</div>

    <div class="keep__item clr_red">
		<div class="keep__item-info">
			<div class="keep__item-info-header"><a href="#" class="btn">1,5x</a><a href="#" class="btn">2x</a></div>
			<div class="keep__item-info-text">Лазерная технология оружия</div>
			<div class="keep__item-info-close">
                <i class="ico">
                    <svg class="svg" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path fill="#ffffff" d="M415.7,397.8l2.72-2.72a2.349,2.349,0,0,0-3.323-3.322l-2.719,2.719-2.719-2.719a2.349,2.349,0,0,0-3.322,3.322l2.719,2.72-2.719,2.719a2.349,2.349,0,0,0,3.322,3.323l2.719-2.72,2.719,2.72a2.35,2.35,0,0,0,3.323-3.323Z" transform="translate(-402.406 -387.813)"/></svg>
                </i>
                <span class="value">Отмена</span>
            </div>
		</div>
		<div class="keep__item-preview">
			<div style="height:30%;" class="keep__item-preview-progress">
                <i>
                    <svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81Z" transform="translate(4.5 4.5)"/></svg>
                </i>
            </div>
			<div class="keep__item-preview-frame">
                <i>
                    <svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
                </i>
            </div>
			<div class="keep__item-preview-ico">
                <i>
                    <svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
                </i>
            </div>
		</div>
		<div class="keep__item-timer"><span><i>09:35</i></span></div>
	</div>
    <!--
	<div class="keep__item clr_red">
		<div class="keep__item-preview">
			<div class="keep__item-preview-frame"><i><img src="/img/keep/factories-ready.svg" alt="" class="svg"/></i></div>
		</div>
	</div>
    -->
	<div class="keep__item clr_red">
		<div class="keep__item-preview">
			<div class="keep__item-preview-frame"><i><img src="/img/keep/factories-locked.svg" alt="" class="svg"/></i></div>
		</div>
	</div>
    
</div>
