<div class="game game_login">
    <div class="game__login">
        <div class="game__login-header">
            <div class="title">КОЛОНИЗАТОРЫ</div>
            <div class="subtitle">Первая браузерная игра с пенальным выводом средств</div>
			<div class="text">Начни завоевывать вселенную уже сегодня. Десятки тысяч планет и тысячи игроков<br>жду тебя в сражение тысячелетия</div>
        </div>
        <div class="game__login-enter">
            <?= $this->login ?>
			<?= $this->register ?>
        </div>
        <div class="game__login-footer">
        </div>
    </div>
</div>
