<div class="game game_login">
    <div class="game__login clearfix">
        <div class="game__galaxy"></div>
        <div class="game__login-logo"><img src="/img/logo.png"></div>
        <div class="game__login-enter">
            <?= $this->login ?>
			<?= $this->register ?>
        </div>
        <div class="game__login-header">
            <div class="subtitle">The first browserify game with really output of cash</div>
            <div class="text">To begin achive universe right now. Many thouthands of planets and thouthands players<br>have awaiting for you into battles of millenium</div>
        </div>
        <div class="game__login-footer">
            <a href="#" class="game__login-footer-link" data-popup=".popup_contacts">Contacts</a>
            <a href="#" class="game__login-footer-link" data-popup=".popup_support">Support service</a>
            <a href="#" class="game__login-footer-link" data-popup=".popup_rules">Rules of game</a>
            <a href="#" class="game__login-footer-link" data-popup=".popup_confident">Politic of confident</a>
            <a href="#" class="game__login-footer-link" data-popup=".popup_conditions">Use conditions of resource</a>
        </div>
    </div>
</div>
