<form action="/doauth" method="post" class="game__login-form game__login-form_auth is-closed">
							<div class="enter">
								<div class="enter__close">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 17 17">
  <path fill="#8D8FA9" d="M1451.65,596.01a1.379,1.379,0,0,0-.99.413l-4.17,4.165-4.17-4.165a1.379,1.379,0,0,0-.99-0.413,1.419,1.419,0,0,0-1,.413l-1.92,1.922a1.41,1.41,0,0,0,0,1.993l4.16,4.165-4.16,4.165a1.411,1.411,0,0,0,0,1.994l1.92,1.922a1.422,1.422,0,0,0,1,.412,1.382,1.382,0,0,0,.99-0.412l4.17-4.166,4.17,4.166a1.407,1.407,0,0,0,1.99,0l1.92-1.922a1.393,1.393,0,0,0,0-1.994l-4.16-4.165,4.16-4.165a1.392,1.392,0,0,0,0-1.993l-1.92-1.922a1.385,1.385,0,0,0-1-.413" transform="translate(-1438 -596)"/>
</svg> 
                                </div>
								<div class="enter__title">
                                    <i class="ico">
                                        <img src="/img/ico/ico-auth.svg">
                                    </i> 
                                    Enter
                                </div>
								<div class="enter__form">
									<div class="enter__system">
										<div class="enter__system-wrap">
											<div class="enter__system-ico">
                                                <img src="/img/ico/ico-input-system.svg">
                                            </div> 
                                            <input type="hidden" value="0" name="authSystem">
											<div class="enter__system-current">
                                                Stars system
                                            </div>
											<div class="enter__system-list js-scroll-wrap">
												<div data-value="1" class="enter__system-item">
                                                    Sun system
                                                </div>
											</div>
											<div class="enter__system-handle">
                                                <img src="/img/ico/ico-input-dropdown.svg">
                                            </div>
										</div>
									</div>
									<div data-form="field" class="enter__form-field">
										<div class="enter__form-input">
                                            <input type="text" name="login" placeholder="Login" data-required="true" />
											<div class="enter__form-controls">
												<div class="enter__form-controls-clear">
                                                    <img src="/img/ico/ico-input-clear.svg" />
                                                </div>
												<div class="enter__form-controls-notepad">
                                                    <img src="/img/ico/ico-input-notepad.svg" />
                                                </div>
											</div>
											<div class="enter__form-status"></div>
											<div data-form="message" class="enter__form-message"></div>
										</div>
									</div>
									<div data-form="field" class="enter__form-field">
										<div class="enter__form-input"> 
                                            <input type="password" name="password" placeholder="Password" data-required="true" />
											<div class="enter__form-controls">
												<div class="enter__form-controls-clear">
                                                    <img src="/img/ico/ico-input-clear.svg" />
                                                </div>
												<div class="enter__form-controls-notepad">
                                                    <img src="/img/ico/ico-input-notepad.svg" />
                                                </div>
											</div>
											<div class="enter__form-status"></div>
											<div data-form="message" class="enter__form-message"></div>
											<div class="enter__form-footnote">
                                                <a href="#" class="enter__form-footnote-link">
                                                    Forget your password?
                                                </a>
                                            </div>
										</div>
									</div>
									<div class="enter__footnote"></div>
									<div class="enter__submit">
										<div class="enter__submit-btn js-submit-form">Enter</div>
									</div>
								</div>
							</div>
						</form>
