<form action="/doregister" method="post" class="game__login-form game__login-form_reg is-closed">
							<div class="enter">
								<div class="enter__close"><svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 17 17">
  <path fill="#8D8FA9" d="M1451.65,596.01a1.379,1.379,0,0,0-.99.413l-4.17,4.165-4.17-4.165a1.379,1.379,0,0,0-.99-0.413,1.419,1.419,0,0,0-1,.413l-1.92,1.922a1.41,1.41,0,0,0,0,1.993l4.16,4.165-4.16,4.165a1.411,1.411,0,0,0,0,1.994l1.92,1.922a1.422,1.422,0,0,0,1,.412,1.382,1.382,0,0,0,.99-0.412l4.17-4.166,4.17,4.166a1.407,1.407,0,0,0,1.99,0l1.92-1.922a1.393,1.393,0,0,0,0-1.994l-4.16-4.165,4.16-4.165a1.392,1.392,0,0,0,0-1.993l-1.92-1.922a1.385,1.385,0,0,0-1-.413" transform="translate(-1438 -596)"/>
</svg> 
                                </div>
								<div class="enter__title">Registration</div>
								<div class="enter__form">
									<div data-form="field" class="enter__form-field">
										<div class="enter__form-input"> 
                                            <input type="text" name="login" placeholder="Name" data-required="true" />
											<div class="enter__form-controls">
												<div class="enter__form-controls-clear">
                                                    <img src="/img/ico/ico-input-clear.svg" />
                                                </div>
												<div class="enter__form-controls-notepad">
                                                    <img src="/img/ico/ico-input-notepad.svg" />
                                                </div>
											</div>
											<div class="enter__form-status"></div>
											<div data-form="message" class="enter__form-message"></div>
										</div>
									</div>
									<div data-form="field" class="enter__form-field">
										<div class="enter__form-input"> 
                                            <input type="text" name="email" placeholder="Email" data-required="email" />
											<div class="enter__form-controls">
												<div class="enter__form-controls-clear">
                                                    <img src="/img/ico/ico-input-clear.svg" />
                                                </div>
												<div class="enter__form-controls-notepad">
                                                    <img src="/img/ico/ico-input-notepad.svg" />
                                                </div>
											</div>
											<div class="enter__form-status"></div>
											<div data-form="message" class="enter__form-message"></div>
										</div>
									</div>
									<div data-form="field" class="enter__form-field">
										<div class="enter__form-input"> <input type="password" name="password" placeholder="Password" data-required="true" />
											<div class="enter__form-controls">
												<div class="enter__form-controls-clear">
                                                    <img src="/img/ico/ico-input-clear.svg" />
                                                </div>
												<div class="enter__form-controls-notepad">
                                                    <img src="/img/ico/ico-input-notepad.svg" />
                                                </div>
											</div>
											<div class="enter__form-status"></div>
											<div data-form="message" class="enter__form-message"></div>
											<div class="enter__form-footnote">
                                                <a href="#" class="enter__form-footnote-link">How can I fit password?</a>
												<div class="enter__form-footnote-tooltip">
													<div class="title">How can I make secure password?</div>
													<div class="text js-scroll-wrap">
														<p>To do unique password to every accounts. To use letters ever registers (big and little). To append numerous and service symbols.</p>
														<p>To invent long password - it is main rule. “Long and secure password does not be without meaning. - Explaining tech expert.</p>
													</div>
												</div>
											</div>
										</div>
									</div>
									<div data-form="field" class="enter__form-field">
										<div class="enter__form-input"> 
                                            <input type="text" name="planet" placeholder="Your planet" data-required="true" />
											<div class="enter__form-controls">
												<div class="enter__form-controls-clear">
                                                    <img src="/img/ico/ico-input-clear.svg" />
                                                </div>
												<div class="enter__form-controls-notepad">
                                                    <img src="/img/ico/ico-input-notepad.svg" />
                                                </div>
											</div>
											<div class="enter__form-status"></div>
											<div data-form="message" class="enter__form-message"></div>
										</div>
									</div>
                                    <div class="enter__system">
										<div class="enter__system-wrap">
											<div class="enter__system-ico"><img src="/img/ico/ico-input-system.svg"></div> <input type="hidden" value="0" name="regSystem">
											<div class="enter__system-current">Star system</div>
											<div class="enter__system-list js-scroll-wrap">
												<div data-value="1" class="enter__system-item">Sun system</div>
											</div>
											<div class="enter__system-handle"><img src="/img/ico/ico-input-dropdown.svg"></div>
										</div>
									</div>
									<div class="enter__footnote">Registering you approve with<br> <a data-popup=".popup_conditions" href="#">Use conditions</a></div>
									<div class="enter__submit">
										<div class="enter__submit-btn js-submit-form">Continue</div>
									</div>
								</div>
							</div>
						</form>
