<div id="popupMarket3" class="popup popup_blackmarket">
    <div class="popup__overlay"></div>
    <div class="popup__inner">
        <div class="popup__layout">
            <div class="popup__close"></div>
            <div class="popup__title">Покупка доната</div>
            <div class="popup__head">
                <div class="popup__head-menu">
                    <div class="popup__head-menu-group">
                        <a href="#" class="popup__head-menu-item is-active"
                           data-entity="valute-button"
                           data-sign="$"
                        >
                            <span>usd</span>
                        </a>
                        <a href="#" class="popup__head-menu-item"
                           data-entity="valute-button"
                           data-sign="€"
                        >
                            <span>eur</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="popup__market popup__market_donut">
                <div class="popup__market-content js-scroll-wrap">
                    <div class="storage">
                        <div class="storage__list" 
                             data-donate_price_usd="<?= $donate_price ?>"
                             data-donate_price_eur="<?= $donate_price / $dollar_euro_course ?>"
                             data-dollar_euro_course="<?= $dollar_euro_course ?>"
                             data-currency_sign="$"
                             data-currency_usd_sign="$"
                             data-currency_eur_sign="€"
                        >
                        <?php foreach(array(10, 30, 50, 100, 200, 500, 1000) as $amount) : ?>
                            <div class="storage__card" data-donate_amount="<?= $amount ?>">
                                <div class="storage__card-inner">
                                    <div class="storage__card-ico">
                                        <div class="ico ico-resource"><img src="/img/ico_resurses/ico_resurce-09.svg" alt=""></div>
                                    </div>
                                    <div class="storage__card-title">Темная м.</div>
                                    <div class="storage__card-fill"><b><?= $amount ?></b></div>
                                    <div class="storage__card-text">Стоимость <br>
                                        <span class="donut">
                                            <div class="val"
                                                 data-entity="valute-amount"
                                            >
                                                <?= number_format($amount / $donate_price, 0, "", " ") ?> $
                                            </div>
                                        </span> 
                                    </div>
                                    <a href="#" data-entity="buy-donate" class="storage__card-buy storage__card-buy_violet">Купить</a> 
                                </div>
                            </div>
                        <?php endforeach; ?>
                            <div class="storage__card" data-donate_amount="1000000">
                                <div class="storage__card-inner">
                                    <div class="storage__card-ico">
                                        <div class="ico ico-resource"><img src="/img/ico_resurses/ico_resurce-09.svg" alt=""></div>
                                    </div>
                                    <div class="storage__card-title">Темная м.</div>
                                    <div class="storage__card-counter">
                                        <div class="counter">
                                            <div data-entity="donate-minus-sign" class="counter__arrow counter__arrow_down"></div>
                                            <div class="counter__value"
                                                 data-entity="donate-amount"
                                            >
                                                 1 000 000
                                            </div>
                                            <div data-entity="donate-plus-sign" class="counter__arrow counter__arrow_up"></div>
                                        </div>
                                    </div>
                                    <div class="storage__card-text">Стоимость <br>
                                        <div class="counter">
                                            <div data-entity="money-minus-sign" class="counter__arrow counter__arrow_down"></div>
                                            <div class="counter__value"
                                                 data-entity="valute-amount"
                                            >
                                                <?= number_format(1000000. / $donate_price, 0, "", " ") ?> $
                                            </div>
                                            <div data-entity="money-plus-sign" class="counter__arrow counter__arrow_up"></div>
                                        </div>
                                    </div>
                                    <a href="#" data-entity="buy-donate" class="storage__card-buy storage__card-buy_violet">Купить</a> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup__market-footer"><span>Покупка 245 000 ТМ</span><span>Стоимость 1000 Р</span><span>Скида 100 Р</span></div>
            </div>
        </div>
    </div>
</div>
