<div class="popup popup_buy">
    <div class="popup__overlay"></div>
    <div class="popup__inner">
        <div class="popup__layout">
            <div class="popup__close"></div>
            <div class="popup__title">Игровые покупки</div>
            <div class="popup__market">
                <div class="popup__market-content js-scroll-wrap">
                    <div class="storage">
                        <div class="storage__list">
                            <div class="buy__pay">
                                <div class="buy__pay-result"
                                     data-entity="total_4_buy"
                                     data-total_4_buy_donate="0"
                                >
                                    К оплате: 15 000 Р.
                                </div>
                                <div class="buy__pay-title">Способ оплаты</div>
                                <div class="buy__pay-list">
                                    <div class="buy__pay-item">
                                        <div class="buy__pay-inner">
                                            <div class="buy__pay-logo"><i class="ico"><img src="/img/ico/ico-buy-visa.svg" alt="Visa" class="svg"></i></div>
                                            <div class="buy__pay-name">Visa</div>
                                        </div>
                                    </div>
                                    <div class="buy__pay-item">
                                        <div class="buy__pay-inner">
                                            <div class="buy__pay-logo"><i class="ico"><img src="/img/ico/ico-buy-mastercard.svg" alt="Master Card" class="svg"></i></div>
                                            <div class="buy__pay-name">Master Card</div>
                                        </div>
                                    </div>
                                    <div class="buy__pay-item">
                                        <div class="buy__pay-inner">
                                            <div class="buy__pay-logo"><i class="ico"><img src="/img/ico/ico-buy-maestro.svg" alt="Maestro Card" class="svg"></i></div>
                                            <div class="buy__pay-name">Maestro Card</div>
                                        </div>
                                    </div>
                                    <div class="buy__pay-item">
                                        <div class="buy__pay-inner">
                                            <div class="buy__pay-logo"><i class="ico"><img src="/img/ico/ico-buy-apple.svg" alt="Apple Pay" class="svg"></i></div>
                                            <div class="buy__pay-name">Apple Pay</div>
                                        </div>
                                    </div>
                                    <div class="buy__pay-item">
                                        <div class="buy__pay-inner">
                                            <div class="buy__pay-logo"><i class="ico"><img src="/img/ico/ico-buy-wm.svg" alt="WebMoney" class="svg"></i></div>
                                            <div class="buy__pay-name">WebMoney</div>
                                        </div>
                                    </div>
                                    <div class="buy__pay-item">
                                        <div class="buy__pay-inner">
                                            <div class="buy__pay-logo"><i class="ico"><img src="/img/ico/ico-buy-qiwi.svg" alt="Qiwi" class="svg"></i></div>
                                            <div class="buy__pay-name">Qiwi</div>
                                        </div>
                                    </div>
                                    <div class="buy__pay-item">
                                        <div class="buy__pay-inner">
                                            <div class="buy__pay-logo"><i class="ico"><img src="/img/ico/ico-buy-yandex.svg" alt="Яндекс деньги" class="svg"></i></div>
                                            <div class="buy__pay-name">Яндекс деньги</div>
                                        </div>
                                    </div>
                                    <a href="#" data-entity="buy-donate-end" class="storage__card-buy storage__card-buy_violet">Купить</a>
                                </div>                                        
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
