<div class="popup popup_conditions">
			<div class="popup__inner">
				<div class="popup__layout">
					<div class="popup__close"></div>
					<div class="popup__title">Conditions</div>
					<div class="popup__content js-scroll-wrap">
						<div class="popup__text">
                            <h1>Standard Terms and Conditions of Use</h1>

</h4>1 Scope and Subject of the Terms and Conditions of Use</h4>


About us: Empire of Intellectual Systems and Technologies LP, 
Suite 1, 4 Queen Street, 
Edinburgh, Scotland UK. 


1.1 These Standard Terms and Conditions of Use ("Terms and Conditions of Use") regulate the use of the online games and other services, such as forums and support systems (the " Fear Universe Services"), provided by  Company4D GmbH, Albert-Nestler-Straße 8, 76131 Karlsruhe ("Fear Universe").
1.2 The Company Services are aimed to be used exclusively by consumers. The Company Services can be used either in the form of free online games and services or as online games and services where certain virtual articles and rights can be acquired in return for a payment. In some cases the Company Services can also be used in return for a one- or regular fee ("Membership"). Unless these Terms and Conditions of Use explicitly provide otherwise, they likewise apply to the paid the Company Services, including the membership.
The paid acquisition of virtual articles or rights and membership arrangements are the additional subject to the Special Terms and Conditions for the Paid Acquisition of Virtual Articles and the Arrangement of Fee-based Membership ("Special Conditions").
1.3 The Company is entitled to interrupt the provision of the Services without prior notice if there are urgent technical reasons or necessary maintenance works. In all other cases reasonable advance notice will be provided using suitable means. 
1.4 The Company Services may only be used in the currently valid version.
1.5 The Company Services are solely intended for the entertainment purposes of consumers. It is prohibited to use them for the purpose of making a gainful profit. Exceptions to this require prior written consent of the Company.
1.6 The user is responsible for the timely update and compatibility of his software and hardware, particularly, for the purpose of using new releases or other updates of the Company Services.
1.7 The Company Services are the subject to the applicable rules of gaming or use ("Rules"), if any of them exist and outline the Company rights of possession and ownership in detail. If there are any contradictions between the Terms and Conditions of Use and the Rules, these Terms and Conditions will have priority, unless the Rules are accorded priority in the specific case.
1.8 The user's contrary rules or standard terms and conditions will not apply.


<h4>2 General provisions concerning the conclusion of contract</h4>
2.1 In order to use the Company Services the user must be registered. On top of that the user must be registered in order to save game statistics.
2.2 The registration is permitted only for individuals (groups, families, spouses etc. are not allowed).
The registration form must be filled in personally. The registration by third parties is forbidden.
2.3 Minors are only permitted to use the Company Services with the consent of their relevant legal guardian and at the age over the minimum level indicated in the relevant age rating.
2.4 During the registration process the user must enter certain data such as a player name and an email address registered in his name. The user has no right to be assigned a particular player name. The player name may not infringe any third-party rights or any relevant legal regulations nor may it offend public decency. Only user is responsible for the implementation of this paragraph. Aside from that, it is not permitted to use an email or web address as a player name. The information provided by the user at the time of registration must be fully truthful and complete. The user is obliged to continually update the information provided at the registration. If required for the execution of the license agreement, the Company is entitled to demand a relevant ID which will be deleted promptly right after verification.
2.5 By entering necessary data on one of the Company’s web pages, the user submits an offer to conclude the license agreement regulated herein. The Company accepts the offer by activating the user account. The Company is entitled to make the activation of the user account dependent on the user validating his email address (opt-in procedure). This is performed by the Company sending the user an email confirming the receipt of the offer and containing a request for the user to validate his email address. At the time of the activation performed by the Company, a license agreement will be established between the Company and the user in accordance with these Terms and Conditions of Use. In some cases the registration process may be different from that described here - particularly when registering via third-party websites (such as social media). In such cases the user will be instructed on how to submit the contractual declaration required for the license agreement.
2.6 As an alternative to the registration via web pages, the Company may enable registration via relevant functions of other websites or social media (e.g. "Facebook Connect"). In this context, once the user gives his consent to the relevant website operator, his personal data may be relayed to the Company. Use of this kind of registration procedure requires the user to be registered with the applicable website or social media in accordance with the rules and regulations applicable there. The provisions of Section 2 correspondingly apply for the conclusion of contract.
2.7 There are no recommended standarts to registration or activation.
2.8 Once the registration completes, the user creates a user account which he can independently administer. The user may create an account on the Company portal or on the relevant website. The user can also use the user account created on Fear Universe portal for all other online games linked by the Company with its portal. Unless otherwise indicated when creating the user account, the user account created on an online game page is solely intended for that online game on the page on which the account was created; it cannot be used for other online games. The Company reserves the right to implement technical arrangements (e.g. in the form of a portal) that enable user accounts to be simultaneously used for several Company Services.
2.9 The user account may not be transferred or made available to other parties without the consent of the Company..

<h4>3 General duties of the user</h4>
3.1 Log-in data, usernames, passwords
3.1.1 The user is obliged to keep his log-in data secret at all times. In particular the user is obliged to only use his log-in data within the Company Services and to protect it from unauthorized third-party access.
3.1.2 "Log-in data" is the user's personal access data used to authenticate him and to preclude any use by unauthorized third parties. The password may not be identical to the player name and must contain at least eight characters comprising a combination of digits and letters.
3.1.3 If the user has any reason to suspect that a third party has or could have gained unauthorized use of this data, he must promptly inform the Company and change his data or have it changed by the Company. This problem can make the Company temporarily block access to the user. The same thing may happen when the Company has any indication that the data is being misused. The user renews his access to the account once the suspicion of misuse becomes groundless.
3.1.4
Unless permitted under the Rules, the user is not entitled under any circumstances to use the log-in data of another user.
3.2 The use of the Company Services
3.2.1 The Company Services include contents of all kinds which are protected under trademark law, copyright or otherwise protected in favour of the Company or in favour of third parties. Without a permission from by the Company, the user is not entitled to modify, reproduce or publicly distribute the Company Services or the content made available therein, nor may he use these for advertising or any other purpose other than the contractually agreed one. Reproduction is only permitted where this is technically necessary for the purpose of using the Company Services as contractually agreed. It is not permissible to modify, conceal or remove copyright notices and trademark names.
3.2.2 The word "Content" involves all data, images, texts, graphics, musical pieces, sounds, sound sequences, videos, programs or software code and any other information provided by the Company. "Content" also includes all services available for download.
3.2.3 The user should refrain from any action that could jeopardize or interrupt the normal conduct of the Company Services. He should also desist from accessing data which he is not supposed to use.
3.2.4 The user is not allowed to publish contents beyond the ambit of the Country Services.
3.2.5 It is prohibited to use the Country Services via anonymous servers or similar means capable of hiding the real IP address or the origin of the user.
3.3 Use of the client software
The Company provides users with services which require pre-installation of the client software, a non-exclusive right to install and use the client software limited by the duration of the licence agreement to enable their use. A user is only permitted to reproduce the client software insofar as this is necessary for the contractually compliant use of the software. Any form of the commercial use of the software is prohibited. 
Any modification of the client software or the reverse copying the program code into  other code forms (decompilation), reproduction of the supplied program code as well as any other forms of reverse engineering of the various software production phases are prohibited to the extent these are not required to obtain the information necessary to establish interoperability of the client software with other programs, and if the establishment of interoperability cannot be otherwise demanded particularly from the Company and the relevant data is not used for any purpose other than establishing interoperability and these actions are performed by the user only.

<h4>4 Special conditions for the use of the online games</h4>
4.1  A user may participate in each round of an online game using one user account only unless the rules allow exceptions. It is not permissible to use multiple user accounts ("multi-accounts"). The company is entitled at any time at its own discretion to block or delete unauthorised multi-accounts.
4.2 A user is prohibited to interfere in the online game in any way for the pupose of manipulation. A user is not entitled, in particular, to take any measures, use mechanisms or software that could interfere in the functionality or the course of the game. A user is prohibited to take measures that could result in an unreasonable or excessive load on the technical capacities. A user is not permitted to block, rewrite or modify the content generated by the Company or to interfere in the online game in any other manner.
4.3 A user is also prohibited to run the online game together with other programs apart from the internet browser or the supplied client program. This especially refers to bots or other tools that are designed to replace or augment the web interface. It is prohibited to use scripts and programs that give a user an advantage over his co-players. 
Under no circumstances may the user
a) create or use cheats, mods, hacks and/or software that alter the online game experience
b) use software that facilitates "data mining" or otherwise captures or collects information in connection with the online games
c) buy or sell virtual articles originating from the Company Services from third parties in return for real means of payment, nor may he exchange these goods or attempt to negotiate any of the aforementioned transactions unless this is permissible in the individual case.
This also includes all actions equivalent to the aforementioned prohibited activities.
 4.4 All rights to the virtual articles used in the online games and acquired in return for payment belong exclusively to the Company except those cases when they are used in accordance with these Terms and Conditions of Use.
4.5 It is not permissible to use private servers, i.e. servers held by users or third parties that enable, establish or maintain unauthorised connections to the Company Services, particularly by means of programs, the use of which has not been explicitly approved by the Company, or which emulate or attempt to emulate the Company Services.

<h4>
    5 Special conditions for the use of communications facilities (in particular discussion forum, chat, blog and comment functions)
</h4>
5.1 The Company may provide the user with various communication facilities for its own content and contributions, which the user may use within the terms of the relevant availability. The Company in this respect solely provides the technical facilities for the exchange of information. There is no entitlement to the provision of such communication facilities.
5.2 The user is prohibited to publish or disseminate content (e.g. images, videos, links, names, texts) within the the Company Services, if this
a) violates the applicable law or is unethical;
b) infringes trademarks, patents, copyright, other industrial property rights, business secrets or other third-party rights;
c) is obscene, racist, glorifies violence, is pornographic or liable to corrupt the young or otherwise endanger or impair the development of children and young people;
d) is insulting, harassing, libellous in character or is otherwise prejudicial to an individual's rights of personality;
e) contains chain letters or pyramid schemes;
f) creates the false impression of being provided by or supported by the Company;
g) contains the personal data of third parties who have not consented to its inclusion;
h) is commercial in character, particularly having an advertising effect.
5.3 The user is obliged moreover to choose appropriate wording and not to disseminate any political or religious content or content with sexual references.
5.4 The Company does not claim any ownership to the content provided by users. The user nevertheless grants the Company the permanent, irrevocable and non-exclusive right to use the content and contributions made by him within the ambit of the Company Services. The Company indicates that the content entered is at best subject to active sampling checks, but this is not a seamless monitoring method. The user, moreover, has the possibility of reporting to the Company content that is possibly illegal. The Company will thereupon respond promptly and, insofar as required, will edit or delete the reported content.

<h4>
6 Consequences of a breach of duty
</h4>
6.1 If the Company objects to particular content, the user must promptly remove it if there is any doubt. the Company reserves the right to remove this content itself.
6.2 Notwithstanding all other statutory or contractual rights, particularly the right of termination for cause pursuant to Section 8.2 of these Terms and Conditions of Use, using its discretion the Company may undertake one or more of the following actions if there are actual circumstances that genuinely indicate that a user has violated these Terms and Conditions of Use or the relevant applicable supplementary conditions and Rules, unless the user is not responsible for the violation:
a) amend or delete content,
b) issue a warning to the relevant user,
c) announce the misconduct in the relevant online game and disclose the player name,
d) temporarily block the user account and
e) exclude the relevant user, including for future cases.
6.3 Once a user has been excluded, he may not register a new user account without the prior consent of the Company.

<h4>
7 Disclaimer
</h4>
7.1 the Company is liable according to the statutory provisions for damage/loss sustained by the user and caused deliberately or through the gross negligence of the Company or its vicarious agents. It is likewise liable for personal injury and damage within the definition of the Product Liability Law.
7.2 Otherwise the Company's liability in relation to compensation claims – irrespective of the legal basis – is limited in accordance with the following provisions, unless otherwise provided for under a guarantee made by the Company:
7.2.1 In relation to damage/loss caused by ordinary negligence, the Company shall only be liable insofar as the matter relates to a breach of material contractual duties. Material contractual duties are those contractual obligations the fulfilment of which is strictly necessary in order that the agreement can be duly executed, whereby the user should normally be able to rely on these duties being fulfilled. In the event that the Company is hereby liable for ordinary negligence, the liability the Company will be limited to that damage/loss which is foreseeable and typical for this type of agreement.
7.2.2 The liability of the Company in relation to data and/or programs lost due to the Company's ordinary negligence shall be limited to the typical recovery costs that would have been sustained by the user had he implemented regular data backup measures which are reasonable in view of all the circumstances.

<h4>
8 Contractual term; deletion of user accounts
</h4>
8.1 Unless otherwise explicitly stated during the registration procedure, the agreement for the use of the the Company Services shall be concluded for an indefinite period. Provided no fixed term has been agreed, both parties are entitled at any time to cancel the agreement for convenience with a notice period of two weeks. If a fixed term was agreed, the agreement can only be cancelled for convenience upon expiry of the term. If no cancellation is issued, the applicable fixed-term agreement shall be automatically extended by the originally agreed term.
8.2 Each party has the right to terminate the agreement for cause without notice, if a material reason exists. A material reason is specifically established if
a) the user is in default of payment of fees and fails to pay despite having received a reminder or if the user uses paid the Company Services without authorisation,
b) there are actual circumstances that indicate that his conduct is significantly and negatively impacting on the gaming experience of other users,
c) the user materially breaches laws, the provisions contained in Sections 3, 4 or 5 of these Terms and Conditions of Use, supplementary applicable conditions and/or Rules, unless he is not responsible for the violation.
8.3 Every cancellation/termination must be communicated in writing. Cancellations issued by email satisfy the written form requirement. Cancellations may also be issued using the cancel function integrated into the web page of the online game in question.
8.4 the Company is authorised to delete the user account if there are grounds justifying this (e.g. if user accounts without a membership are inactive for longer periods of time). The respective reasons and pre-conditions for deleting user accounts may be read in the Rules – if in existence – of the online game in question. Furthermore, the Company is entitled at its own discretion to delete user accounts at the end of the agreement.
8.5 If the Company has issued notice to terminate the licence agreement for cause for reasons for which the user is not responsible or if it ceases operating the respective the Company Services prior to a cancellation becoming effective, the user shall be entitled to demand the equivalent value paid by him for the Premium currency credit balance still on the user account or the remaining period of the membership.

<h4>
9 Applicable law, Court
The contractual relationship is governed by English law to the exclusion of the United Nations Convention on Contracts for the International Sale of Goods and the referral regulations of international private law. If, at the time of the relevant conclusion of contract (registration, purchase of paid services), the user as a consumer has as his usual domicile a location in another country within the European Union, the validity of the strictly applicable legal regulations of the country in question shall remain unaffected by the choice of law made in the 1st sentence.
</h4>

<h4>
10 Amendments to these Terms and Conditions of Use, Miscellaneous, Communication, Severability Clause
</h4>
10.1 the Company reserves the right to amend these Terms and Conditions of Use. The Company will notify the user by email of the amended conditions at least four weeks before these coming into effect and it shall inform the user of the proposed applicability of these new Terms and Conditions of Use as well as the right of the user to object to their applicability. If the user does not object to the applicability of the new Terms and Conditions of Use within this period or if he again logs into the the Company Services after the amended Terms and Conditions of Use have come into effect, these amended conditions shall be deemed accepted. the Company will notify the user of the implications of the four-week period, the right to object and the legal consequences of failing to respond using a suitable form.
10.2 The user is only entitled to perform an offset if his counter-claim is legally enforceable (by way of a res judicata decision) or has been authorised or is not disputed by the Company. The user may only exercise a right of retention of his claims are established under this agreement.
10.3 The Company as a rule shall communicate with the user by email – unless other provided for within these Terms and Conditions of Use. The user shall ensure that the email address used for the registration is regularly checked for messages from the Company. If the user contacts the Company, he must state to which online game and which user account he is referring. the Company shall provide the user with a support system for support issues. the Company is entitled to instruct the user to communicate exclusively via the support system regarding support issues.
10.4 If any individual provisions of these Terms and Conditions of Use should prove to be unenforceable, the remaining provisions shall remain enforceable. The unenforceable provision shall be substituted for the relevant statutory provision.
 
						</div>
					</div>
				</div>
			</div>
			<div class="popup__overlay"></div>
		</div>
