<div class="popup popup_contacts">
			<div class="popup__inner">
				<div class="popup__layout">
					<div class="popup__close"></div>
					<div class="popup__title">Contacts</div>
					<div class="popup__content js-scroll-wrap">
						<div class="popup__text">
							<h1>Name & Registered Office:</h1>
                            <ul>
                                <li>EMPIRE OF INTELLECTUAL SYSTEMS AND TECHNOLOGIES LP</li>
                                <li>SUITE 1</li> 
                                <li>4 QUEEN STREET</li> 
                                <li>EDINBURGH</li> 
                                <li>SCOTLAND UK</li> 
                                <li>EH2 1JE</li> 
                                <li>Company No. SL030847</li>
                            </ul>
                            <h4>Status: Active</h4>
                            <p>Date of registration: 06/04/2017</p>
						</div>
					</div>
				</div>
			</div>
			<div class="popup__overlay"></div>
		</div>
