<div class="popup popup_fleet popup_fleet_2">
            <!-- join -->
			<div class="popup__inner">
				<div class="popup__layout">
					<div class="popup__close"></div>
					<div class="popup__title">Отправка флота</div>
					<div class="popup__head">
                        <a data-popup=".popup_fleet_1" href="#" class="popup__head-item popup__head-item_back"><span>Назад</span></a>
						<div class="popup__head-group"><a href="#" class="popup__head-item"><i class="ico"><img src="/img/ico/simp-ico-rocket.svg" alt="" class="svg"></i> <span>Флот</span></a><a href="#" class="popup__head-item is-active"><i class="ico"><img src="/img/ico/simp-ico-attack.svg" alt="" class="svg"></i> <span>Цель</span></a>
							<a href="#" class="popup__head-item is-disable"><i class="ico"><img src="/img/ico/simp-ico-flag.svg" alt="" class="svg"></i> <span>Задание</span></a>
						</div><a data-popup=".popup_fleet_3" href="#" class="popup__head-item popup__head-item_next"><span>Далее</span></a> </div>
					<div class="popup__content">
						<div class="popup__content-aside">
							<div class="fleet__deliver">
								<div class="fleet__deliver-item">
									<div class="fleet__deliver-title">Откуда</div>
									<div class="fleet__deliver-view"><span></span>
										<div class="fleet__deliver-dim" data-entity="fstc_LightYears">Расстояние<br>- свет лет</div>
									</div>
									<div class="fleet__deliver-text">Ваша планеты</div>
									<div class="fleet__deliver-title"><?= $currentPlanet->getName() ?></div>
								</div>
								<div class="fleet__deliver-item">
									<div class="fleet__deliver-title">Куда</div>
									<div class="fleet__deliver-view"><span></span></div>
									<div class="fleet__deliver-text">Планеты</div>
									<div class="fleet__deliver-planet">
										<div class="sselect">
											<div class="sselect-wrap"> <input type="hidden" value="0" name="regSystem">
												<div class="sselect-current">Мои планеты</div>
												<div class="sselect-list js-scroll-wrap">
                                                    <?php foreach($mplanets as $planet) : ?>
                                                    <div data-value="<?= $planet->getId()?>" class="sselect-item"><?= $planet->getName()?></div>
                                                    <?php endforeach; ?>
												</div>
												<div class="sselect-handle"><img src="/img/ico/ico-input-dropdown.svg"></div>
											</div>
										</div>
									</div>
									<div class="fleet__deliver-text">Координаты</div>
									<div class="fleet__deliver-coordinates">
                                        <input type="text" data-target_entity="galaxy" value="4" class="fleet__deliver-coordinates-item">
                                        <input type="text" data-target_entity="planet_system" value="102" class="fleet__deliver-coordinates-item">
                                        <input type="text" data-target_entity="planet" value="1" class="fleet__deliver-coordinates-item">
                                    </div>
								</div>
							</div>
						</div>
						<div class="popup__content-inner js-scroll-wrap">
							<div class="fleet__info">
								<div class="fleet__info-title">Информация о задании</div>
								<div class="fleet__info-text">
									<p>Время полета в одну сторону <span class="fl-r clr_white" data-entity="fstc_Time2OneEnd">-</span></p>
									<p>Потребление топлива в одну сторону <span class="fl-r clr_white" data-entity="fstc_SpendFuelAtOneEnd">-</span></p>
									<p>Скорость полета (макс 5000) <span class="fl-r clr_white" data-entity="fstc_Speed">-</span></p>
								</div>
								<div class="fleet__info-text">
									<p>Прибытие <span class="fl-r clr_white" data-entity="fstc_Arrival">-</span></p>
									<p>Возврат <span class="fl-r clr_white" data-entity="fstc_Comeback">-</span></p>
									<p>Грузоподьемность <span class="fl-r clr_white" data-entity="fstc_Capacity">-</span></p>
								</div>
								<div class="fleet__info-title">Скорость полета</div>
								<div class="fleet__info-speed">
									<div class="fleet__info-speed-range">
										<div class="range">
											<div class="range__counter">
												<div class="counter">
													<div class="counter__down"></div>
													<div class="counter__value">52</div>
													<div class="counter__up"></div>
												</div>
											</div>
											<div data-range-max="5000" data-range-val="км/ч" class="range__slider">
												<div class="range__current"></div>
												<div class="range__max"></div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="popup__overlay"></div>
            <!-- join -->
		</div>
