<!--include popups/popup-planet-->
		<div id="popupBuilding" class="popup popup_building">
			<div class="popup__overlay"></div>
			<div class="popup__inner">
				<div class="popup__layout">
					<div class="popup__close"></div>
					<div class="popup__title">Строительство</div>
					<div class="popup__head">
						<div class="popup__head-menu">
							<div class="popup__head-menu-group">
                                <?php $i=0; foreach($tabs as $tab) : $i++; ?>
                                    <a class="popup__head-menu-item <?= ($i==1) ? 'is-active' : '';?>" data-tab-link="<?=$tab['building_tab']?>" data-tab-group="building_group">
                                        <i class="ico ico_menu <?= $tab['ico']; ?>"></i>
                                        <span><?=$this->translate($tab['name'])?></span>
                                    </a>
                                <?php endforeach; ?>
                            </div>
						</div>
					</div>
					<div class="popup__image"></div>
                    <?php $i=0; foreach($tabs as $tab) : $i++; ?>
					<div class="popup__tabs <?= ($i==1) ? 'is-active' : '';?>" data-tab-targ="<?=$tab['building_tab']?>" data-tab-group="building_group">
						<div class="popup__tabs-menu">
                        <?php if(isset($tab['sub_tabs']))  : ?>
                            <?php $j=0; foreach($tab['sub_tabs'] as $building_type => $sub_tab) : $j++; ?>
                            <div data-tab-link="<?= $buildins_types[$building_type]['building_tab']; ?>" data-tab-group="<?= $tab['building_tab']?>" class="popup__tabs-menu-item <?= ($j==1) ? 'is-active' : '';?>">
                                <span><?= $buildins_types[$building_type]['name']; ?></span>
                            </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
						</div>
						<div class="popup__tabs-content js-scroll-hor">
                            <?php if(isset($tab['sub_tabs']))  : ?>
                            <?php $j=0; foreach($tab['sub_tabs'] as $building_type => $sub_tab) : $j++; ?>
                            <div 
                                data-tab-targ="<?= $buildins_types[$building_type]['building_tab']; ?>" 
                                data-tab-group="<?= $tab['building_tab']?>" 
                                class="popup__tabs-content-item <?= ($j==1) ? 'is-active' : '';?>"
                            >
                                <div class="storage">
                                    <div class="storage__list">
										<?php foreach($sub_tab as $building) : ?>
                                        <div class="storage__card build__item"
                                            data-entity="<?= $tab['name']; ?>"
                                            data-root="<?= $tab['name']; ?>-build-block-main"
                                            data-item_identifier="<?= $building->getId(); ?>"
                                            data-building_period="<?= $building->temp_building_period; ?>"
                                            data-building_level="<?= $building->temp_current_level; ?>"
                                            data-building_price_factor="<?= $building->getPriceFactor(); ?>"
                                            data-summ_resource_consume="<?= $building->getConsumeAll(); ?>"
                                            data-consume_metall="<?= $building->getConsumeMetall(); ?>"
                                            data-consume_heavygas="<?= $building->getConsumeHeavygas(); ?>"
                                            data-consume_ore="<?= $building->getConsumeOre(); ?>"
                                            data-consume_hydro="<?= $building->getConsumeHydro(); ?>"
                                            data-consume_titan="<?= $building->getConsumeTitan(); ?>"
                                            data-consume_darkmatter="<?= $building->getConsumeDarkmatter(); ?>"
                                            data-consume_redmatter="<?= $building->getConsumeRedmatter(); ?>"
                                            data-consume_anti="<?= $building->getConsumeAnti(); ?>"
                                            data-power_factor="<?= $building->getPowerFactor(); ?>"
                                            data-total_donate_needle="<?= $building->temp_total_donate_needle; ?>"
                                            >
                                            <div class="storage__card-inner">
                                                <div class="storage__card-clear ico ico_set ico_close"></div>
                                                <div style="color: #eabd3d;" class="storage__item storage__item_done">
                                                    <div class="storage__item-inner">
                                                        <div class="storage__item-frame"><svg class="storage_ico" xmlns="http://www.w3.org/2000/svg" width="54" height="54" viewBox="0 0 54 54">
      <path class="storage_ico-lock" d="M422.132,45.652h-0.178V44.3a2.88,2.88,0,0,0-5.76,0v1.355h-0.178A1.352,1.352,0,0,0,414.661,47v3.038a1.352,1.352,0,0,0,1.355,1.35h6.116a1.353,1.353,0,0,0,1.355-1.35V47A1.353,1.353,0,0,0,422.132,45.652ZM417.9,44.3a1.175,1.175,0,0,1,2.349,0v1.355H417.9V44.3Z" transform="translate(-392 -19.094)"/>
      <path class="storage_ico-ready" d="M423.8,46.1l-1.6,1.646a0.675,0.675,0,0,1-.972,0l-3.848-3.95a1.378,1.378,0,0,1-.389-1l0.031-1.343a0.658,0.658,0,0,1,.654-0.652l1.4,0.007a1.313,1.313,0,0,1,.933.4l3.791,3.891A0.72,0.72,0,0,1,423.8,46.1Zm-4.725.993-3.48,3.572a0.336,0.336,0,0,1-.483,0L414.1,49.631a0.357,0.357,0,0,1,0-.5l3.48-3.572Z" transform="translate(-392 -19.094)"/>
      <path class="storage_ico-inner" d="M419,25.863A19.927,19.927,0,1,1,399,45.79a19.986,19.986,0,0,1,20-19.927" transform="translate(-392 -19.094)"/>
      <path class="storage_ico-frame" d="M419,21.191A24.909,24.909,0,1,1,394,46.1a24.983,24.983,0,0,1,25-24.909" transform="translate(-392 -19.094)"/>
    </svg> 
                                                        </div>
                                                        <div class="storage__item-ico">
                                                            <?= $building->getPicture() ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="storage__card-title">
                                                    <div data-entity="keep__item-text"><?= $building->getName();?></div>
                                                    <div data-entity="keep__item-lvl">(<?= $building->getCurrentLevel($planet, null, $buildingRepository) + 1 ?>)</div>
                                                </div>
                                                <div style="display:none;" data-entity="building-description"><?= $building->getDescription() ?></div>
                                                <div class="storage__card-btns">
                                                    <div class="btn">1,5x</div>
                                                    <div class="btn">2x</div>
                                                </div>
                                                <div class="storage__card-counter">
                                                    <div class="counter">
                                                        <div class="counter__arrow counter__arrow_down"></div>
                                                        <div class="counter__value">2</div>
                                                        <div class="counter__arrow counter__arrow_up"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <?php endforeach; ?>
									</div>
								</div>
							</div>
                            <?php endforeach; ?>
                            <?php endif; ?>
						</div>
					</div>
                    <?php endforeach; ?>
				</div>
			</div>
		</div>
<!--
<div class="popup popup_building">
    <div class="popup__inner">
        <div class="popup__layout">
            <div class="popup__close"></div>
            <div class="popup__title"><?=$this->translate('Construction')?></div>
            <div class="popup__head">
                <?php $i=0; foreach($tabs as $tab) : $i++; ?>
                    <span class="popup__head-item <?= ($i==1) ? 'is-active' : '';?>" data-tab-link="<?=$tab['building_tab']?>" data-tab-group="building_group">
                        <i class="ico">
                            <img src="<?= $tab['image']?>" alt="" class="svg">
                        </i>
                        <span><?=$this->translate($tab['name'])?></span>
                    </span>
                <?php endforeach; ?>
            </div>
            <?php $i=0; foreach($tabs as $tab) : $i++; ?>
            <div class="popup__content <?= ($i==1) ? 'is-active' : '';?>" data-tab-targ="<?=$tab['building_tab']?>" data-tab-group="building_group">
                <div class="popup__content-image"></div>
                <div class="tabs">
                    <div class="tabs__menu">
                    <?php if(isset($tab['sub_tabs']))  : ?>
                        <?php $j=0; foreach($tab['sub_tabs'] as $building_type => $sub_tab) : $j++; ?>
                        <div data-tab-link="<?= $buildins_types[$building_type]['building_tab']; ?>" data-tab-group="<?= $tab['building_tab']?>" class="tabs__item <?= ($j==1) ? 'is-active' : '';?>"><?= $buildins_types[$building_type]['name']; ?></div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </div>
                    <div class="tabs__content js-scroll-hor">
                    <?php if(isset($tab['sub_tabs']))  : ?>
                        <?php $j=0; foreach($tab['sub_tabs'] as $building_type => $sub_tab) : $j++; ?>
                        <div 
                            data-tab-targ="<?= $buildins_types[$building_type]['building_tab']; ?>" 
                            data-tab-group="<?= $tab['building_tab']?>" 
                            class="build__list <?= ($j==1) ? 'is-active' : '';?>"
                        >
                            <?php foreach($sub_tab as $building) : ?>
                                <div class="build__item"
                                    data-entity="srcbuilding"
                                    data-root="resources-build-block-main"
                                    data-item_identifier="<?= $building->getId() ?>"
                                    data-building_period="<?= $building->getBuildingPeriodByLevel($building->getCurrentLevel($planet, null, $buildingRepository) + 1) ?>"
                                    data-building_level="<?= $building->getCurrentLevel($planet, null, $buildingRepository) + 1 ?>"
                                    data-building_price_factor="<?= $building->getPriceFactor() ?>"
                                    data-summ_resource_consume="<?= $building->getConsumeAll() ?>"
                                    data-consume_metall="<?= $building->getConsumeMetall(); ?>"
                                    data-consume_heavygas="<?= $building->getConsumeHeavygas(); ?>"
                                    data-consume_ore="<?= $building->getConsumeOre(); ?>"
                                    data-consume_hydro="<?= $building->getConsumeHydro(); ?>"
                                    data-consume_titan="<?= $building->getConsumeTitan(); ?>"
                                    data-consume_darkmatter="<?= $building->getConsumeDarkmatter(); ?>"
                                    data-consume_redmatter="<?= $building->getConsumeRedmatter(); ?>"
                                    data-consume_anti="<?= $building->getConsumeAnti(); ?>"
                                    data-power_factor="<?= $building->getPowerFactor(); ?>"
                                    >
                                    <div class="keep__item clr_red">
                                        <?= $building->getPicture() ?>
                                        <div class="keep__item-text"><span data-entity="keep__item-text"><?= $building->getName() ?></span></div>
                                        <div class="keep__item-lvl"><span>lv. <?= $building->getCurrentLevel($planet, null, $buildingRepository) + 1 ?></span></div>
                                    </div>
                                    <div style="display:none;" data-entity="building-description"><?= $building->getDescription() ?></div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
            <div class="popup__pp" data-entity="popup_building-popup__pp" data-building_id="" data-root="" data-picture="" data-color="">
                <div class="popup__pp-layout">
                    <div class="popup__pp-close"></div>
                    <div class="popup__pp-preview">
                        <div class="popup__pp-control">
                            <div class="btn btn_big btn_border">Древо технологий</div>
                        </div>
                    </div>
                    <div class="popup__pp-content">
                        <div class="popup__pp-content__title" 
                            data-entity="popup_building-popup__pp-layout-popup__pp-content-title">
                            Ракетостроительный<br>завод&nbsp;<span class="btn btn_lvl">lv.1</span>
                        </div>
                        <div class="popup__pp-content__text">
                            Время исследования : 
                            <span data-entity="popup_building-popup__pp-layout-popup__pp-building-period" class="clr_white">40m 0c</span>
                        </div>
                        <div class="popup__pp-content__text"
                            data-entity="popup_building-popup__pp-layout-popup__pp-content-description">
                            Будет освоено производство межконтинентальных ракет баллистических и оперативно - тактических ракет для комплексов "Ярс-М", "Булава" и "Искандер"
                        </div>
                        <div class="popup__pp-content__text"
                            data-entity="popup_building-popup__pp-layout-popup__pp-content-needles">
                        </div>
                        <div class="popup__pp-control">
                            <div class="btn btn_big btn_dark">Описание</div>
                            <div data-entity="popup_building-popup__pp-popup__pp-control-build-button" class="btn btn_big btn_red">Строить</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="popup__overlay"></div>
</div>
-->
<div class="popup popup_ship" data-building_id="" data-root="" data-picture="" data-color="">
    <div class="popup__overlay"></div>
    <div class="popup__inner">
        <div class="popup__layout">
            <div class="popup__close"></div>
            <div class="popup__header">
                <div class="popup__header-subtitle">Строительство</div>
                <div class="popup__header-title">Малый десантный корабль</div>
            </div>
            <div class="popup__content">
                <div class="popup__content-text">
                    <p>Имеет возможность атаковать флот противника ракетами и бомбами<br>Открывает:</p>
                    <ul>
                        <li>- <a href="#">Сверхзвуковые ракеты</a><br></li>
                        <li>- <a href="#">Ракеты дальнего действия</a><br></li>
                        <li>- <a href="#">Вакумные бомба</a></li>
                    </ul>
                </div>
                <div class="popup__content-info">
                    <div class="popup__content-info-title">Уровень 3</div>
                    <div class="popup__content-info-text">XP 340 / 1000</div>
                    <div class="popup__content-info-list">
                        <div class="popup__content-info-item"><i class="ico ico_info ico_heart"></i><span class="val">100</span></div>
                        <div class="popup__content-info-item"><i class="ico ico_info ico_sword"></i><span class="val">42</span></div>
                        <div class="popup__content-info-item"><i class="ico ico_info ico_shield"></i><span class="val">30</span></div>
                        <div class="popup__content-info-item"><i class="ico ico_info ico_speed"></i><span class="val">9</span></div>
                        <div class="popup__content-info-item"><i class="ico ico_info ico_connect"></i><span class="val">14</span></div>
                    </div>
                </div>
                <div class="popup__content-grid"></div>
                <div class="popup__content-tax">
                    <div class="popup__content-tax-counter">
                        <div class="popup__content-tax-title">Кол-во:</div>
                        <div class="counter">
                            <div class="counter__arrow counter__arrow_down is-disable"></div>
                            <div class="counter__value">1</div>
                            <div class="counter__arrow counter__arrow_up"></div>
                        </div>
                    </div>
                    <div class="popup__content-tax-resourses">
                        <div class="popup__content-tax-title">Требуется для производства</div>
                        <div class="resourses">
                            <div class="resourses__list">
                                <div class="resourses__item"><i class="ico"><img src="/img/ico_resurses/ico_resurce-01.svg" alt=""></i><span class="val">1000</span></div>
                                <div class="resourses__item"><i class="ico"><img src="/img/ico_resurses/ico_resurce-02.svg" alt=""></i><span class="val">350</span></div>
                                <div class="resourses__item"><i class="ico"><img src="/img/ico_resurses/ico_resurce-03.svg" alt=""></i><span class="val">50</span></div>
                                <div class="resourses__item"><i class="ico"><img src="/img/ico_resurses/ico_resurce-04.svg" alt=""></i><span class="val">700</span></div>
                                <div class="resourses__item"><i class="ico"><img src="/img/ico_resurses/ico_resurce-05.svg" alt=""></i><span class="val">5</span></div>
                            </div>
                        </div>
                    </div>
                    <div class="popup__content-tax-timer">
                        <div class="popup__content-tax-title">Время производства</div>
                        <div class="time"><i class="ico ico_info ico_watch"></i><span class="val" data-entity="period">00:30:23</span></div>
                    </div>
                </div>
            </div>
            <div class="popup__footer">
                <div class="popup__footer-left">
                    <div class="btn"><i class="ico ico_action ico_back"></i> Древо технологий</div>
                </div>
                <div class="popup__footer-middle">
                    <div class="btn" data-entity="popup_ship_build_button">Строить</div>
                </div>
                <div class="popup__footer-right">
                    <div class="popup__footer-donut">
                        <span>Купить за</span>
                        <span class="donut">
                            <i class="ico"><img src="/img/ico_resurses/ico_resurce-09.svg" alt=""></i>
                            <span class="val" data-entity="total_donate_needle">505</span>
                        </span>
                    </div>
                    <div class="popup__footer-buy" data-entity="building_4_donate_building_button">
                        <a href="#" class="ico ico-cartw"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
