<div class="popup popup_orbit">
			<div class="popup__inner">
				<div class="popup__layout">
					<div class="popup__close"></div>
					<div class="popup__title">Звездная система</div>
					<div class="popup__head">
						<div class="popup__head-name">Галактика</div>
						<div class="popup__head-counter">
							<div class="popup__head-counter-arrow popup__head-counter-arrow_prev"></div>
							<div class="popup__head-counter-field">
								<div class="counter">
									<div class="counter__down"></div>
									<div class="counter__value">010</div>
									<div class="counter__up"></div>
								</div>
							</div>
							<div class="popup__head-counter-arrow popup__head-counter-arrow_next"></div>
						</div>
						<div class="popup__head-name">Система</div>
						<div class="popup__head-counter">
							<div class="popup__head-counter-arrow popup__head-counter-arrow_prev"></div>
							<div class="popup__head-counter-field">
								<div class="counter">
									<div class="counter__down"></div>
									<div class="counter__value">102</div>
									<div class="counter__up"></div>
								</div>
							</div>
							<div class="popup__head-counter-arrow popup__head-counter-arrow_next"></div>
						</div>
						<div class="popup__head-btn"><a href="#" class="btn btn_big">Перейти</a></div>
					</div>
					<div class="popup__content">
						<div class="system">
							<div class="system__menu"><a href="#" class="system__menu-item system__menu-item_prev">Система 101</a>
								<div class="system__menu-item system__menu-item_current">Система 102</div><a href="#" class="system__menu-item system__menu-item_next">Система 103</a> </div>
							<div class="system__orbit js-scroll-hor">
								<div class="system__orbit-inner">
									<div class="system__orbit-sphere">
										<div class="sphere">
											<div class="sphere__item sphere__item_cold"></div>
											<div class="sphere__item sphere__item_norm"></div>
											<div class="sphere__item sphere__item_norm"></div>
											<div class="sphere__item sphere__item_norm"></div>
											<div class="sphere__item sphere__item_norm"></div>
											<div class="sphere__item sphere__item_norm"></div>
											<div class="sphere__item sphere__item_warm"></div>
											<div class="sphere__item sphere__item_burn"></div>
										</div>
									</div>
									<div class="system__orbit-list system__orbit-list_burn">
										<div class="system__orbit-status">Слишком горячо</div>
										<div class="system__orbit-solar">
											<div class="solar solar_small"></div>
										</div>
										<div class="system__orbit-item">
											<div class="planet">
												<div class="planet__item planet__item_search"></div>
											</div>
										</div>
									</div>
									<div class="system__orbit-list system__orbit-list_warm">
										<div class="system__orbit-status">Горячо</div>
										<div class="system__orbit-item">
											<div class="planet">
												<div class="planet__satellite planet__satellite_top">
													<div class="planet__satellite-item"></div>
													<div class="planet__satellite-item"></div>
													<div class="planet__satellite-item"></div>
													<div class="planet__satellite-item"></div>
												</div>
												<div class="planet__item planet__item_fill"></div>
												<div class="planet__satellite planet__satellite_bottom">
													<div class="planet__satellite-item"></div>
													<div class="planet__satellite-item"></div>
													<div class="planet__satellite-item"></div>
													<div class="planet__satellite-item"></div>
												</div>
												<div class="planet__info planet__info_top">
													<div class="planet__info-head"><a href="#" class="link"><i class="ico"><img src="/img/ico/ico-search.svg" alt="" class="svg"></i><span>Посмотреть</span></a></div>
													<div class="planet__info-name">Нептун</div>
												</div>
												<div class="planet__info planet__info_bottom">
													<div class="planet__info-status"></div>
													<div class="planet__info-links"><a href="#" class="link"><i class="ico"><img src="/img/ico/ico-person.svg" alt="" class="svg"></i><span>UserName</span></a><a href="#" class="link"><i class="ico"><img src="/img/ico/ico-orden.svg	" alt="" class="svg"></i><span>TeamGroup</span></a></div>
													<div class="planet__info-message"><a href="#" class="link"><i class="ico"><img src="/img/ico/ico-messages.svg" alt="" class="svg"></i><span>Сообщения</span></a></div>
													<div class="planet__info-coord">&#216;12.800 км<br>от 11Сo до 29Сo <br> Место [1:39:10]</div>
												</div>
											</div>
										</div>
									</div>
									<div class="system__orbit-list system__orbit-list_norm">
										<div class="system__orbit-status clr_white">Благоприятная зона</div>
										<div class="system__orbit-item">
											<div class="planet">
												<div class="planet__item"></div>
												<div class="planet__satellite planet__satellite_bottom">
													<div class="planet__satellite-item"></div>
												</div>
												<div class="planet__info planet__info_top">
													<div class="planet__info-head"><a href="#" title="Смотреть" class="link"><i class="ico"><img src="/img/ico/simp-ico-eye.svg" alt="" class="svg"></i></a><a href="#" title="Обделаться" class="link"><i class="ico"><img src="/img/ico/simp-ico-bomb.svg" alt="" class="svg"></i></a>
														<a
														 href="#" title="Атаковать" class="link"><i class="ico"><img src="/img/ico/simp-ico-attack.svg" alt="" class="svg"></i></a>
													</div>
													<div class="planet__info-name">Нептун</div>
												</div>
												<div class="planet__info planet__info_bottom">
													<div class="planet__info-status is-attacked"></div>
													<div class="planet__info-links"><a href="#" class="link"><i class="ico"><img src="/img/ico/ico-person.svg" alt="" class="svg"></i><span>UserName</span></a><a href="#" class="link"><i class="ico"><img src="/img/ico/ico-orden.svg	" alt="" class="svg"></i><span>TeamGroup</span></a></div>
													<div class="planet__info-coord">&#216;12.800 км<br>от 11Сo до 29Сo <br> Место [1:39:10]</div>
												</div>
											</div>
										</div>
										<div class="system__orbit-item">
											<div class="planet">
												<div class="planet__item"></div>
												<div class="planet__satellite planet__satellite_bottom">
													<div class="planet__satellite-item"></div>
													<div class="planet__satellite-item"></div>
												</div>
												<div class="planet__info planet__info_top">
													<div class="planet__info-head"><a href="#" class="link"><i class="ico"><img src="/img/ico/simp-ico-flag.svg" alt="" class="svg"></i><span>Посмотреть</span></a></div>
													<div class="planet__info-name">Нептун</div>
												</div>
												<div class="planet__info planet__info_bottom">
													<div class="planet__info-status"></div>
													<div class="planet__info-coord">&#216;12.800 км<br>от 11Сo до 29Сo <br> Место [1:39:10]</div>
												</div>
											</div>
										</div>
										<div class="system__orbit-item">
											<div class="planet">
												<div class="planet__item"></div>
												<div class="planet__satellite planet__satellite_bottom">
													<div class="planet__satellite-item"></div>
													<div class="planet__satellite-item"></div>
													<div class="planet__satellite-item"></div>
												</div>
											</div>
										</div>
										<div class="system__orbit-item">
											<div class="planet">
												<div class="planet__item"></div>
											</div>
										</div>
										<div class="system__orbit-item">
											<div class="planet">
												<div class="planet__item"></div>
												<div class="planet__satellite planet__satellite_bottom">
													<div class="planet__satellite-item"></div>
													<div class="planet__satellite-item"></div>
													<div class="planet__satellite-item"></div>
													<div class="planet__satellite-item"></div>
												</div>
											</div>
										</div>
									</div>
									<div class="system__orbit-list system__orbit-list_cold">
										<div class="system__orbit-status">Холодно</div>
										<div class="system__orbit-item">
											<div class="planet">
												<div class="planet__item"></div>
												<div class="planet__satellite planet__satellite_bottom">
													<div class="planet__satellite-item"></div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="popup__overlay"></div>
		</div>
