<div class="popup popup_fleet popup_fleet_2">
			<div class="popup__inner">
				<div class="popup__layout">
					<div class="popup__close"></div>
					<div class="popup__title">Отправка флота</div>
					<div class="popup__head">
                        <a data-popup=".popup_fleet_1" href="#" class="popup__head-item popup__head-item_back"><span>Назад</span></a>
						<div class="popup__head-group"><a href="#" class="popup__head-item"><i class="ico"><img src="/img/ico/simp-ico-rocket.svg" alt="" class="svg"></i> <span>Флот</span></a><a href="#" class="popup__head-item is-active"><i class="ico"><img src="/img/ico/simp-ico-attack.svg" alt="" class="svg"></i> <span>Цель</span></a>
							<a href="#" class="popup__head-item is-disable"><i class="ico"><img src="/img/ico/simp-ico-flag.svg" alt="" class="svg"></i> <span>Задание</span></a>
						</div><a data-popup=".popup_fleet_3" href="#" class="popup__head-item popup__head-item_next"><span>Далее</span></a> </div>
					<div class="popup__content">
						<div class="popup__content-aside">
							<div class="fleet__deliver">
								<div class="fleet__deliver-item">
									<div class="fleet__deliver-title">Откуда</div>
									<div class="fleet__deliver-view"><span></span>
										<div class="fleet__deliver-dim">Расстояние<br>23 т свет лет</div>
									</div>
									<div class="fleet__deliver-text">Ваша планеты</div>
									<div class="fleet__deliver-title">Terra Nova</div>
								</div>
								<div class="fleet__deliver-item">
									<div class="fleet__deliver-title">Куда</div>
									<div class="fleet__deliver-view"><span></span></div>
									<div class="fleet__deliver-text">Планеты</div>
									<div class="fleet__deliver-planet">
										<div class="sselect">
											<div class="sselect-wrap"> <input type="hidden" value="0" name="regSystem">
												<div class="sselect-current">Звездная система</div>
												<div class="sselect-list js-scroll-wrap">
													<div data-value="1" class="sselect-item">Солнечная система</div>
													<div data-value="2" class="sselect-item">Система подачи топлива</div>
													<div data-value="3" class="sselect-item">Система аналитики</div>
													<div data-value="5" class="sselect-item">Солнечная система</div>
													<div data-value="6" class="sselect-item">Система здравоохранения</div>
													<div data-value="1" class="sselect-item">Солнечная система</div>
													<div data-value="2" class="sselect-item">Система подачи топлива</div>
													<div data-value="3" class="sselect-item">Система аналитики</div>
													<div data-value="5" class="sselect-item">Солнечная система</div>
													<div data-value="6" class="sselect-item">Система здравоохранения</div>
													<div data-value="1" class="sselect-item">Солнечная система</div>
													<div data-value="2" class="sselect-item">Система подачи топлива</div>
													<div data-value="3" class="sselect-item">Система аналитики</div>
													<div data-value="5" class="sselect-item">Солнечная система</div>
													<div data-value="6" class="sselect-item">Система здравоохранения</div>
												</div>
												<div class="sselect-handle"><img src="/img/ico/ico-input-dropdown.svg"></div>
											</div>
										</div>
									</div>
									<div class="fleet__deliver-text">Координаты</div>
									<div class="fleet__deliver-coordinates"> <input type="text" name="" value="4" class="fleet__deliver-coordinates-item"> <input type="text" name="" value="102" class="fleet__deliver-coordinates-item"> <input type="text" name="" value="" class="fleet__deliver-coordinates-item"> </div>
								</div>
							</div>
						</div>
						<div class="popup__content-inner js-scroll-wrap">
							<div class="fleet__info">
								<div class="fleet__info-title">Информация о задании</div>
								<div class="fleet__info-text">
									<p>Время полета в одну сторону <span class="fl-r clr_white">1 день 12:45:51</span></p>
									<p>Потребление топлива в одну сторону <span class="fl-r clr_white">5 (14%)</span></p>
									<p>Скорость полета (макс 5000) <span class="fl-r clr_white">5000</span></p>
								</div>
								<div class="fleet__info-text">
									<p>Прибытие <span class="fl-r clr_white">28.11.22  21:40:52</span></p>
									<p>Возврат <span class="fl-r clr_white">29.11.22  21:40:52</span></p>
									<p>Грузоподьемность <span class="fl-r clr_white">175 000</span></p>
								</div>
								<div class="fleet__info-title">Скорость полета</div>
								<div class="fleet__info-speed">
									<div class="fleet__info-speed-range">
										<div class="range">
											<div class="range__counter">
												<div class="counter">
													<div class="counter__down"></div>
													<div class="counter__value">52</div>
													<div class="counter__up"></div>
												</div>
											</div>
											<div data-range-max="5000" data-range-val="км/ч" class="range__slider">
												<div class="range__current"></div>
												<div class="range__max"></div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="popup__overlay"></div>
		</div>
