<div class="popup popup_shop">
			<div class="popup__inner">
				<div class="popup__layout">
					<div class="popup__close"></div>
					<div class="popup__title">Игровые покупки</div>
					<div class="popup__head"><a href="#" class="popup__head-item is-active"><span>Рубли</span></a><a href="#" class="popup__head-item"><span>Доллары</span></a><a href="#" class="popup__head-item"><span>Евро</span></a><a href="#" class="popup__head-item"><span>Чешская крона</span></a></div>
					<div class="popup__content">
						<div class="popup__menu">
							<div class="popup__menu-item"><a href="#" class="btn">ПРЕДМЕТЫ</a></div>
							<div class="popup__menu-item"><a href="#" class="btn is-active">КОРАБЛИ</a></div>
							<div class="popup__menu-item"><a href="#" class="btn">ОФИЦЕРЫ</a></div>
							<div class="popup__menu-item"><a href="#" class="btn">РЕСУРСЫ</a></div>
						</div>
						<div class="popup__shop js-scroll-wrap">
							<div class="popup__shop-list">
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
								<div class="popup__shop-item">
									<div class="popup__shop-title">1000 Легких истребителей</div>
									<div class="popup__shop-logo">
										<div class="keep__item clr_red">
											<div class="keep__item-preview">
												<div class="keep__item-preview-frame"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M81,81H0V0.027L26,11.992V0L51,11.966V0.062L81,13.126V81ZM2,79H79V14.438L53,3.116V15.143L28,3.177V15.116L2,3.151V79Z" transform="translate(4.5 4.5)"/></svg>
</i></div>
												<div class="keep__item-preview-ico"><i><svg class="svg" xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><path d="M33.046,45.79h-5.7V25.576l2.233-6.7h4.466l2.232,6.7V45.79H33.046ZM29.582,16.644V9.827l2.233-8.933,1.231,4.926,1,4.006v6.816H29.582ZM13.952,25.576l2.233-6.7h4.466l2.232,6.7V45.79H13.952V25.576ZM16.185,9.827L18.418,0.9l2.233,8.932v6.816H16.185V9.827ZM0.556,25.576l2.233-6.7H7.255l2.232,6.7V45.79H0.556V25.576ZM2.788,9.827L5.021,0.9,7.254,9.827v6.816H2.788V9.827Z" transform="translate(26.578 21.656)"/></svg>
</i></div>
											</div>
										</div>
									</div>
									<div class="popup__shop-price">140 000 р.</div>
									<div class="popup__shop-sale">Скидка 10%</div>
									<div class="popup__shop-buy">
										<div class="btn">Купить</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="popup__overlay"></div>
		</div>
