<div class="popup popup_support">
			<div class="popup__inner">
				<div class="popup__layout">
					<div class="popup__close"></div>
					<div class="popup__title">Support</div>
					<div class="popup__content js-scroll-wrap">
						<div class="popup__text">
                            <h1>
                                For technical support and refund email 
                                <a href="mailto:eistlp06.04.2017@gmail.com">
                                    eistlp06.04.2017@gmail.com
                                </a>
                            </h1>
						</div>
					</div>
				</div>
			</div>
			<div class="popup__overlay"></div>
		</div>
